#include <crypto/groth16.h>
#include <span.h>
#include <test/util/golden_vector_loader.h>
#include <test/util/zk_test_helpers.h>
#include <uint256.h>

#include <boost/test/unit_test.hpp>

#include <cstdint>
#include <iomanip>
#include <sstream>
#include <vector>

using namespace groth16;
using namespace golden_vectors;
using namespace zk_test;

/**
 * These tests use REAL BLS12-381 Groth16 proofs generated by gnark.
 *
 * They require golden vectors to be generated first:
 *   cd shared-utils/kyc-prover
 *   go build -o gentest ./cmd/gentest
 *   ./gentest -output vectors
 *
 * If vectors are not available, tests are skipped.
 */
BOOST_AUTO_TEST_SUITE(groth16_golden_tests)

BOOST_AUTO_TEST_CASE(groth16_golden_valid_proof)
{
    // Skip if golden vectors not available
    if (!GoldenVectorsAvailable()) {
        BOOST_TEST_MESSAGE("Skipping: Golden vectors not found at " << GetDefaultGoldenVectorsPath());
        BOOST_TEST_MESSAGE("Generate with: cd shared-utils/kyc-prover && ./gentest -output vectors");
        return;
    }

    // Load valid golden vector
    auto golden_opt = LoadGoldenVector("valid");
    BOOST_REQUIRE(golden_opt.has_value());
    const auto& golden = golden_opt.value();

    // Verify we have all required data
    BOOST_REQUIRE(golden.proof_bytes.size() == GROTH16_PROOF_SIZE);
    BOOST_REQUIRE(golden.public_inputs_bytes.size() == GROTH16_FR_SIZE * 4);
    BOOST_REQUIRE(!golden.vk_bytes.empty());

    // DIAGNOSTIC: Print sizes and data
    BOOST_TEST_MESSAGE("=== DIAGNOSTIC INFO ===");
    BOOST_TEST_MESSAGE("Proof size: " << golden.proof_bytes.size());
    BOOST_TEST_MESSAGE("Public inputs size: " << golden.public_inputs_bytes.size());
    BOOST_TEST_MESSAGE("VK size: " << golden.vk_bytes.size());

    // Print each public input as hex
    size_t public_input_count = golden.public_inputs_bytes.size() / 32;
    BOOST_TEST_MESSAGE("Public input count: " << public_input_count);
    for (size_t i = 0; i < public_input_count; i++) {
        std::stringstream hex_str;
        hex_str << "Input[" << i << "]: 0x";
        for (size_t j = 0; j < 32; j++) {
            hex_str << std::hex << std::setw(2) << std::setfill('0')
                   << (int)golden.public_inputs_bytes[i * 32 + j];
        }
        BOOST_TEST_MESSAGE(hex_str.str());
    }

    // Print last 4 bytes of compliance_root (should be pure merkle root now)
    BOOST_TEST_MESSAGE("Last 4 bytes of compliance_root (input[2]): 0x"
        << std::hex << std::setw(2) << std::setfill('0') << (int)golden.public_inputs_bytes[92]
        << std::setw(2) << std::setfill('0') << (int)golden.public_inputs_bytes[93]
        << std::setw(2) << std::setfill('0') << (int)golden.public_inputs_bytes[94]
        << std::setw(2) << std::setfill('0') << (int)golden.public_inputs_bytes[95]);

    // Try to identify EXACTLY where error 3 comes from by testing each condition
    BOOST_TEST_MESSAGE("\nDEBUG: Testing each condition that can return InvalidPublicInputs...");

    // Test 1: public_inputs.empty() check
    BOOST_TEST_MESSAGE("public_inputs.empty() = " << (golden.public_inputs_bytes.empty() ? "true (BAD)" : "false (OK)"));

    // Test 2: size multiple of 32
    BOOST_TEST_MESSAGE("public_inputs.size() % 32 = " << (golden.public_inputs_bytes.size() % 32));

    // Test 3: Count would be calculated here, needs VK parse first
    BOOST_TEST_MESSAGE("Attempting minimal verification to isolate error...");

    // Setup verification context
    VerificationContext ctx{
        .max_root_age = 0,  // Disable root age check for now
        .current_height = 0,
        .anchor_commitment = std::nullopt
    };

    // Verify the real proof
    auto result = VerifyGroth16WithPolicy(
        std::span<const unsigned char>(golden.proof_bytes),
        std::span<const unsigned char>(golden.public_inputs_bytes),
        std::span<const unsigned char>(golden.vk_bytes),
        ctx
    );

    BOOST_TEST_MESSAGE("Verification result: " << static_cast<int>(result));
    BOOST_TEST_MESSAGE("Expected: " << static_cast<int>(VerifyError::OK));

    // This is a REAL proof - should verify successfully
    BOOST_CHECK_MESSAGE(
        result == VerifyError::OK,
        "Golden vector 'valid' should verify successfully. Error: " << static_cast<int>(result)
    );
}

BOOST_AUTO_TEST_CASE(groth16_golden_corrupted_proof)
{
    if (!GoldenVectorsAvailable()) {
        BOOST_TEST_MESSAGE("Skipping: Golden vectors not found");
        return;
    }

    auto golden_opt = LoadGoldenVector("valid");
    BOOST_REQUIRE(golden_opt.has_value());
    auto golden = golden_opt.value();

    VerificationContext ctx{
        .max_root_age = 0,
        .current_height = 0,
        .anchor_commitment = std::nullopt
    };

    // Corrupt the proof by flipping a byte
    BOOST_REQUIRE(golden.proof_bytes.size() > 10);
    golden.proof_bytes[10] ^= 0xFF;

    auto result = VerifyGroth16WithPolicy(
        std::span<const unsigned char>(golden.proof_bytes),
        std::span<const unsigned char>(golden.public_inputs_bytes),
        std::span<const unsigned char>(golden.vk_bytes),
        ctx
    );

    // Corrupted proof should fail verification
    BOOST_CHECK(result != VerifyError::OK);
    BOOST_CHECK_MESSAGE(
        result == VerifyError::InvalidProofFormat || result == VerifyError::PairingFailed,
        "Corrupted proof should fail with InvalidProofFormat or PairingFailed. Got: " << static_cast<int>(result)
    );
}

BOOST_AUTO_TEST_CASE(groth16_golden_wrong_public_inputs)
{
    if (!GoldenVectorsAvailable()) {
        BOOST_TEST_MESSAGE("Skipping: Golden vectors not found");
        return;
    }

    auto golden_opt = LoadGoldenVector("valid");
    BOOST_REQUIRE(golden_opt.has_value());
    auto golden = golden_opt.value();

    VerificationContext ctx{
        .max_root_age = 0,
        .current_height = 0,
        .anchor_commitment = std::nullopt
    };

    // Mutate public inputs (flip byte in asset_id field)
    BOOST_REQUIRE(golden.public_inputs_bytes.size() >= 64);
    golden.public_inputs_bytes[40] ^= 0xFF;

    auto result = VerifyGroth16WithPolicy(
        std::span<const unsigned char>(golden.proof_bytes),
        std::span<const unsigned char>(golden.public_inputs_bytes),
        std::span<const unsigned char>(golden.vk_bytes),
        ctx
    );

    // Wrong public inputs should fail pairing check
    BOOST_CHECK(result != VerifyError::OK);
    BOOST_CHECK_MESSAGE(
        result == VerifyError::PairingFailed,
        "Wrong public inputs should fail pairing. Got: " << static_cast<int>(result)
    );
}

BOOST_AUTO_TEST_CASE(groth16_golden_cross_vk_rejection)
{
    if (!GoldenVectorsAvailable()) {
        BOOST_TEST_MESSAGE("Skipping: Golden vectors not found");
        return;
    }

    // Load two different vectors (they should have different VKs if generated separately)
    // For this test, we'll use the valid vector's proof with the invalid_secret vector's VK
    auto valid_opt = LoadGoldenVector("valid");
    auto invalid_opt = LoadGoldenVector("invalid_secret");

    if (!valid_opt.has_value() || !invalid_opt.has_value()) {
        BOOST_TEST_MESSAGE("Skipping: Need both 'valid' and 'invalid_secret' vectors");
        return;
    }

    const auto& valid = valid_opt.value();
    [[maybe_unused]] const auto& invalid = invalid_opt.value();

    // Both vectors use same circuit, so same VK
    // Instead, let's test with a mock VK of wrong size
    auto wrong_vk = MockVerifyingKey(10); // Different gamma_abc_count

    VerificationContext ctx{
        .max_root_age = 0,
        .current_height = 0,
        .anchor_commitment = std::nullopt
    };

    auto result = VerifyGroth16WithPolicy(
        std::span<const unsigned char>(valid.proof_bytes),
        std::span<const unsigned char>(valid.public_inputs_bytes),
        std::span<const unsigned char>(wrong_vk),  // Wrong VK
        ctx
    );

    // Should fail with wrong VK
    BOOST_CHECK(result != VerifyError::OK);
}

BOOST_AUTO_TEST_CASE(groth16_golden_root_age_enforcement)
{
    if (!GoldenVectorsAvailable()) {
        BOOST_TEST_MESSAGE("Skipping: Golden vectors not found");
        return;
    }

    auto golden_opt = LoadGoldenVector("valid");
    BOOST_REQUIRE(golden_opt.has_value());
    const auto& golden = golden_opt.value();

    // Extract root height from public inputs
    uint32_t root_height = golden.GetRootHeight();
    BOOST_TEST_MESSAGE("Golden vector root height: " << root_height);

    // Test 1: Root too old
    {
        VerificationContext ctx{
            .max_root_age = 100,
            .current_height = static_cast<int>(root_height + 200), // 200 blocks later
            .anchor_commitment = std::nullopt
        };

        auto result = VerifyGroth16WithPolicy(
            std::span<const unsigned char>(golden.proof_bytes),
            std::span<const unsigned char>(golden.public_inputs_bytes),
            std::span<const unsigned char>(golden.vk_bytes),
            ctx
        );

        BOOST_CHECK_MESSAGE(
            result == VerifyError::RootTooOld,
            "Root should be too old (age=200, max=100). Got: " << static_cast<int>(result)
        );
    }

    // Test 2: Root within acceptable age
    {
        VerificationContext ctx{
            .max_root_age = 200,
            .current_height = static_cast<int>(root_height + 100), // 100 blocks later
            .anchor_commitment = std::nullopt
        };

        auto result = VerifyGroth16WithPolicy(
            std::span<const unsigned char>(golden.proof_bytes),
            std::span<const unsigned char>(golden.public_inputs_bytes),
            std::span<const unsigned char>(golden.vk_bytes),
            ctx
        );

        // Should pass age check and verify successfully
        BOOST_CHECK_MESSAGE(
            result == VerifyError::OK,
            "Root should be within acceptable age. Got: " << static_cast<int>(result)
        );
    }
}

BOOST_AUTO_TEST_CASE(groth16_golden_tfr_anchor_enforcement)
{
    if (!GoldenVectorsAvailable()) {
        BOOST_TEST_MESSAGE("Skipping: Golden vectors not found");
        return;
    }

    auto golden_opt = LoadGoldenVector("valid");
    BOOST_REQUIRE(golden_opt.has_value());
    const auto& golden = golden_opt.value();

    // Get the TFR anchor from public inputs
    uint256 correct_anchor = golden.GetTfrAnchor();

    // Test 1: Matching anchor (should pass)
    {
        VerificationContext ctx{
            .max_root_age = 0,
            .current_height = 0,
            .anchor_commitment = MakeUCharSpan(correct_anchor)
        };

        auto result = VerifyGroth16WithPolicy(
            std::span<const unsigned char>(golden.proof_bytes),
            std::span<const unsigned char>(golden.public_inputs_bytes),
            std::span<const unsigned char>(golden.vk_bytes),
            ctx
        );

        BOOST_CHECK_MESSAGE(
            result == VerifyError::OK,
            "Proof with correct anchor should verify. Got: " << static_cast<int>(result)
        );
    }

    // Test 2: Wrong anchor (should fail)
    {
        uint256 wrong_anchor = uint256S("0x1111111111111111111111111111111111111111111111111111111111111111");

        VerificationContext ctx{
            .max_root_age = 0,
            .current_height = 0,
            .anchor_commitment = MakeUCharSpan(wrong_anchor)
        };

        auto result = VerifyGroth16WithPolicy(
            std::span<const unsigned char>(golden.proof_bytes),
            std::span<const unsigned char>(golden.public_inputs_bytes),
            std::span<const unsigned char>(golden.vk_bytes),
            ctx
        );

        BOOST_CHECK_MESSAGE(
            result == VerifyError::AnchorMismatch,
            "Proof with wrong anchor should fail. Got: " << static_cast<int>(result)
        );
    }
}

BOOST_AUTO_TEST_CASE(groth16_golden_invalid_vectors_no_proof)
{
    if (!GoldenVectorsAvailable()) {
        BOOST_TEST_MESSAGE("Skipping: Golden vectors not found");
        return;
    }

    // Invalid vectors should have empty proof_hex (circuit constraints fail)
    std::vector<std::string> invalid_names = {
        "invalid_secret",
        "invalid_age",
        "invalid_country",
        "invalid_merkle"
    };

    for (const auto& name : invalid_names) {
        auto vec_opt = LoadGoldenVector(name);
        if (!vec_opt.has_value()) {
            BOOST_TEST_MESSAGE("Skipping '" << name << "': vector not found");
            continue;
        }

        const auto& vec = vec_opt.value();

        // Invalid vectors should have should_fail=true and empty proof
        BOOST_CHECK_MESSAGE(
            vec.should_fail,
            "Vector '" << name << "' should have should_fail=true"
        );

        BOOST_CHECK_MESSAGE(
            vec.proof_bytes.empty(),
            "Vector '" << name << "' should have empty proof (circuit constraints unsatisfiable)"
        );
    }
}

BOOST_AUTO_TEST_SUITE_END()

/**
 * HDv1 golden vector tests (6-input circuit with output key binding).
 *
 * Requires HDv1 golden vectors:
 *   cd shared-utils/kyc-prover
 *   go run ./cmd/gentest_hd_v1 -output vectors_hd_v1
 */
BOOST_AUTO_TEST_SUITE(groth16_hdv1_golden_tests)

BOOST_AUTO_TEST_CASE(hdv1_golden_valid_proof)
{
    if (!HDV1GoldenVectorsAvailable()) {
        BOOST_TEST_MESSAGE("Skipping: HDv1 golden vectors not found at " << GetDefaultHDV1GoldenVectorsPath());
        return;
    }

    auto golden_opt = LoadHDV1GoldenVector("valid");
    BOOST_REQUIRE(golden_opt.has_value());
    const auto& golden = golden_opt.value();

    // HDv1: 192-byte public inputs (6 x 32)
    BOOST_REQUIRE(golden.proof_bytes.size() == GROTH16_PROOF_SIZE);
    BOOST_REQUIRE(golden.public_inputs_bytes.size() == GROTH16_FR_SIZE * 6);
    BOOST_REQUIRE(golden.IsHDv1());
    BOOST_REQUIRE(!golden.vk_bytes.empty());

    BOOST_TEST_MESSAGE("HDv1 proof size: " << golden.proof_bytes.size());
    BOOST_TEST_MESSAGE("HDv1 public inputs size: " << golden.public_inputs_bytes.size());
    BOOST_TEST_MESSAGE("HDv1 VK size: " << golden.vk_bytes.size());

    // HDv1 does not use root height extraction — skip max_root_age
    VerificationContext ctx{
        .max_root_age = 0, // Unused for HDv1 (freshness checked on-chain)
        .current_height = 0,
        .anchor_commitment = std::nullopt
    };

    auto result = VerifyGroth16WithPolicy(
        std::span<const unsigned char>(golden.proof_bytes),
        std::span<const unsigned char>(golden.public_inputs_bytes),
        std::span<const unsigned char>(golden.vk_bytes),
        ctx
    );

    BOOST_CHECK_MESSAGE(
        result == VerifyError::OK,
        "HDv1 valid proof should verify. Got error: " << static_cast<int>(result)
    );

    // Verify output key extraction works
    auto xonly_key = golden.GetXOnlyOutputKey();
    BOOST_CHECK_MESSAGE(xonly_key.size() == 32, "Should reconstruct 32-byte x-only key");
    BOOST_TEST_MESSAGE("HDv1 output key: " << HexStr(xonly_key));
}

BOOST_AUTO_TEST_CASE(hdv1_golden_invalid_vectors_rejected)
{
    if (!HDV1GoldenVectorsAvailable()) {
        BOOST_TEST_MESSAGE("Skipping: HDv1 golden vectors not found");
        return;
    }

    auto all_vectors = LoadAllHDV1GoldenVectors();
    BOOST_REQUIRE(!all_vectors.empty());

    int invalid_count = 0;
    for (const auto& vec : all_vectors) {
        if (!vec.should_fail) continue;
        ++invalid_count;

        // Invalid vectors should have empty proofs (constraint system unsatisfied)
        BOOST_CHECK_MESSAGE(
            vec.proof_bytes.empty(),
            "HDv1 invalid vector '" << vec.name << "' should have empty proof"
        );

        BOOST_TEST_MESSAGE("HDv1 invalid vector '" << vec.name << "' correctly rejected by prover");
    }

    // Expect at least: invalid_master_key, invalid_derivation, invalid_output_key, invalid_merkle
    BOOST_CHECK_MESSAGE(invalid_count >= 3,
        "Should have at least 3 invalid HDv1 vectors, got " << invalid_count);
}

BOOST_AUTO_TEST_CASE(hdv1_golden_wrong_vk_rejected)
{
    if (!HDV1GoldenVectorsAvailable()) {
        BOOST_TEST_MESSAGE("Skipping: HDv1 golden vectors not found");
        return;
    }

    auto golden_opt = LoadHDV1GoldenVector("valid");
    BOOST_REQUIRE(golden_opt.has_value());
    const auto& valid = golden_opt.value();

    // Corrupt VK bytes
    std::vector<unsigned char> wrong_vk = valid.vk_bytes;
    if (wrong_vk.size() > 10) {
        wrong_vk[10] ^= 0xFF;
    }

    VerificationContext ctx{
        .max_root_age = 0,
        .current_height = 0,
        .anchor_commitment = std::nullopt
    };

    auto result = VerifyGroth16WithPolicy(
        std::span<const unsigned char>(valid.proof_bytes),
        std::span<const unsigned char>(valid.public_inputs_bytes),
        std::span<const unsigned char>(wrong_vk),
        ctx
    );

    BOOST_CHECK(result != VerifyError::OK);
    BOOST_TEST_MESSAGE("HDv1 wrong VK correctly rejected with error: " << static_cast<int>(result));
}

BOOST_AUTO_TEST_CASE(hdv1_golden_corrupted_output_key_rejected)
{
    // Takes a valid proof and corrupts the output key public inputs [4:5].
    // The BLS12-381 pairing check should fail because the public inputs
    // no longer match what the prover committed to.
    if (!HDV1GoldenVectorsAvailable()) {
        BOOST_TEST_MESSAGE("Skipping: HDv1 golden vectors not found");
        return;
    }

    auto golden_opt = LoadHDV1GoldenVector("valid");
    BOOST_REQUIRE(golden_opt.has_value());
    const auto& valid = golden_opt.value();
    BOOST_REQUIRE(valid.public_inputs_bytes.size() == GROTH16_FR_SIZE * 6);

    // Corrupt output_key_high (element 4, bytes 128-159): flip a byte
    std::vector<unsigned char> corrupted_inputs = valid.public_inputs_bytes;
    corrupted_inputs[128 + 20] ^= 0xFF;  // Flip byte in the key half

    VerificationContext ctx{
        .max_root_age = 0,
        .current_height = 0,
        .anchor_commitment = std::nullopt
    };

    auto result = VerifyGroth16WithPolicy(
        std::span<const unsigned char>(valid.proof_bytes),
        std::span<const unsigned char>(corrupted_inputs),
        std::span<const unsigned char>(valid.vk_bytes),
        ctx
    );

    BOOST_CHECK_MESSAGE(
        result == VerifyError::PairingFailed,
        "Corrupted output key should cause pairing failure. Got: " << static_cast<int>(result)
    );
    BOOST_TEST_MESSAGE("HDv1 corrupted output_key_high correctly rejected by verifier");
}

BOOST_AUTO_TEST_CASE(hdv1_golden_corrupted_merkle_root_rejected)
{
    // Takes a valid proof and corrupts the compliance root (element 2).
    // Verifier pairing check should fail.
    if (!HDV1GoldenVectorsAvailable()) {
        BOOST_TEST_MESSAGE("Skipping: HDv1 golden vectors not found");
        return;
    }

    auto golden_opt = LoadHDV1GoldenVector("valid");
    BOOST_REQUIRE(golden_opt.has_value());
    const auto& valid = golden_opt.value();
    BOOST_REQUIRE(valid.public_inputs_bytes.size() == GROTH16_FR_SIZE * 6);

    // Corrupt compliance_root (element 2, bytes 64-95): flip a byte
    std::vector<unsigned char> corrupted_inputs = valid.public_inputs_bytes;
    corrupted_inputs[64 + 10] ^= 0xFF;

    VerificationContext ctx{
        .max_root_age = 0,
        .current_height = 0,
        .anchor_commitment = std::nullopt
    };

    auto result = VerifyGroth16WithPolicy(
        std::span<const unsigned char>(valid.proof_bytes),
        std::span<const unsigned char>(corrupted_inputs),
        std::span<const unsigned char>(valid.vk_bytes),
        ctx
    );

    BOOST_CHECK_MESSAGE(
        result == VerifyError::PairingFailed,
        "Corrupted compliance root should cause pairing failure. Got: " << static_cast<int>(result)
    );
    BOOST_TEST_MESSAGE("HDv1 corrupted compliance_root correctly rejected by verifier");
}

BOOST_AUTO_TEST_SUITE_END()
