// Copyright (c) 2026 TensorCash
// Golden-vector tests for the vendored v3 prompt-binding primitives
// (verification/pow_v3.{h,cpp}, TIP-0003).
//
// The expected values below are LITERAL COPIES of a representative subset of
// the cross-language contract in
// shared-utils/pow-utils/tests/vectors/v3_vectors.json (generated by
// shared-utils/pow-utils/tests/gen_v3_vectors.py). They are hardcoded on
// purpose — never read the json at runtime. If the vendored implementation
// drifts from the shared one, these fail.

#include <boost/test/unit_test.hpp>

#include <test/util/setup_common.h>
#include <verification/pow_v3.h>

#include <crypto/sha256.h>
#include <util/strencodings.h>  // HexStr

#include <array>
#include <cmath>
#include <cstdint>
#include <numeric>
#include <optional>
#include <stdexcept>
#include <string>
#include <vector>

namespace {

// Deterministic vector inputs, mirroring gen_v3_vectors.py:
//   HEADER = bytes(range(76)); VDF = bytes(range(100, 132)); NONCE = bytes(range(32))
std::vector<uint8_t> VectorHeader()
{
    std::vector<uint8_t> v(76);
    std::iota(v.begin(), v.end(), 0);
    return v;
}
std::vector<uint8_t> VectorVdf()
{
    std::vector<uint8_t> v(32);
    std::iota(v.begin(), v.end(), 100);
    return v;
}
std::array<uint8_t, 32> VectorNonce()
{
    std::array<uint8_t, 32> n{};
    std::iota(n.begin(), n.end(), 0);
    return n;
}
const std::string VECTOR_NONCE_HEX{"000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"};

std::string ToHex(const std::array<uint8_t, 32>& bytes)
{
    static const char* hexmap = "0123456789abcdef";
    std::string out;
    out.reserve(64);
    for (uint8_t b : bytes) {
        out.push_back(hexmap[b >> 4]);
        out.push_back(hexmap[b & 0x0F]);
    }
    return out;
}

std::vector<int64_t> Iota64(int64_t first, size_t count)
{
    std::vector<int64_t> v(count);
    std::iota(v.begin(), v.end(), first);
    return v;
}

} // namespace

BOOST_FIXTURE_TEST_SUITE(pow_v3_vectors_tests, BasicTestingSetup)

// ---- §7 step hashing (vectors "step_hash") --------------------------------

BOOST_AUTO_TEST_CASE(step_hash_golden_vectors)
{
    const auto header = VectorHeader();
    const auto vdf = VectorVdf();
    const auto nonce = VectorNonce();
    std::array<uint8_t, 32> nonce_rev{};
    for (size_t i = 0; i < 32; ++i) nonce_rev[i] = nonce[31 - i];

    struct Case {
        const char* name;
        uint32_t tick;
        uint32_t step;
        std::vector<int64_t> ctx;
        const char* precision;
        const uint8_t* nonce;
        size_t message_len;
        const char* sha256;
        double u;
    };
    const Case cases[] = {
        {"short_ctx_no_nonce", 7, 0, {1, 2, 3}, "fp16", nullptr, 2168,
         "55f878f9395d035483de42ab173acf1943816ee9377853a6046df654377c1e52",
         0.974502106430009},
        {"short_ctx_with_nonce", 7, 0, {1, 2, 3}, "fp16", nonce.data(), 2200,
         "fd3a2a54cdc8e5e7d4b328a57828ea8c00439a4dcc1c41c88eee4f872509f36f",
         0.3287693851161748},
        {"mid_window_with_nonce", 123456789, 200, Iota64(1, 299), "bf16", nonce.data(), 2200,
         "edbaf9a49ee3ec1f7814df65b64aa1744a43b964f4062ed66170a9e4ad96239a",
         0.6444355801213533},
        {"full_window_boundary", 4294967295u, 255, Iota64(1000, 256), "fp8_e4m3", nonce_rev.data(), 2204,
         "218fa6b33bdd17bad3553fbf3205354770ddde3c3ba9c6ac57d04abfb7ecddcd",
         0.7017602401319891},
    };

    for (const auto& c : cases) {
        const std::vector<uint8_t> msg = pow_v3::build_step_message(
            header, vdf, c.tick, c.step, c.ctx, c.precision, c.nonce);
        BOOST_CHECK_EQUAL(msg.size(), c.message_len);
        const std::array<uint8_t, 32> digest = pow_v3::step_digest(msg);
        BOOST_CHECK_MESSAGE(ToHex(digest) == c.sha256, std::string(c.name) + ": digest mismatch " + ToHex(digest));
        // Exact double equality: the literal is the shortest round-trip repr
        // of the vector's u_double.
        BOOST_CHECK_MESSAGE(pow_v3::step_u_from_digest(digest) == c.u, std::string(c.name) + ": u mismatch");
    }
}

// ---- §3 extra_flags carrier (vectors "carrier") ---------------------------

BOOST_AUTO_TEST_CASE(carrier_golden_vectors)
{
    const std::string& nh = VECTOR_NONCE_HEX;

    struct Case {
        const char* name;
        std::string extra_flags;
        std::optional<std::string> expected;
    };
    const Case cases[] = {
        {"canonical", "{\"v3\":{\"admission_nonce\":\"" + nh + "\"}}", nh},
        {"non_canonical_whitespace",
         "{ \"z\": 1 , \"v3\" : { \"admission_nonce\" : \"" + nh + "\" } }", nh},
        {"extra_keys_preserved",
         "{\"completion_id\":\"x\",\"proof_purpose\":\"audit\",\"v3\":{\"admission_nonce\":\"" + nh + "\"}}", nh},
        {"empty", "", std::nullopt},
        {"pformat_blob", "{'completion_id': 'x'}", std::nullopt},
        {"non_object", "[1,2,3]", std::nullopt},
        {"v3_key_absent", "{\"v3\":{}}", std::nullopt},
        {"v3_not_object", "{\"v3\":\"str\"}", std::nullopt},
        {"uppercase_hex", "{\"v3\":{\"admission_nonce\":\"" + std::string(64, 'A') + "\"}}", std::nullopt},
        {"wrong_length_63", "{\"v3\":{\"admission_nonce\":\"" + std::string(63, 'a') + "\"}}", std::nullopt},
        {"wrong_length_65", "{\"v3\":{\"admission_nonce\":\"" + std::string(65, 'a') + "\"}}", std::nullopt},
        {"non_hex", "{\"v3\":{\"admission_nonce\":\"" + std::string(64, 'g') + "\"}}", std::nullopt},
        {"non_string_nonce", "{\"v3\":{\"admission_nonce\":123}}", std::nullopt},
        {"duplicate_top_key", "{\"a\":1,\"a\":2,\"v3\":{\"admission_nonce\":\"" + nh + "\"}}", std::nullopt},
        {"duplicate_nested_key",
         "{\"v3\":{\"admission_nonce\":\"" + nh + "\",\"admission_nonce\":\"" + nh + "\"}}", std::nullopt},
    };
    for (const auto& c : cases) {
        const auto got = pow_v3::extract_admission_nonce_hex(c.extra_flags);
        BOOST_CHECK_MESSAGE(got == c.expected,
                            std::string("carrier ") + c.name + ": got " + (got ? *got : "<none>"));
    }

    // oversized: same shape as the "oversized" vector — a pad member pushing
    // the total beyond EXTRA_FLAGS_MAX_BYTES means no nonce claimed; the same
    // JSON below the bound still claims one.
    {
        const std::string big = "{\"pad\":\"" + std::string(pow_v3::EXTRA_FLAGS_MAX_BYTES, 'x') +
                                "\",\"v3\":{\"admission_nonce\":\"" + nh + "\"}}";
        BOOST_CHECK(!pow_v3::extract_admission_nonce_hex(big).has_value());
        const std::string small = "{\"pad\":\"" + std::string(64, 'x') +
                                  "\",\"v3\":{\"admission_nonce\":\"" + nh + "\"}}";
        const auto got = pow_v3::extract_admission_nonce_hex(small);
        BOOST_CHECK(got.has_value() && *got == nh);
    }

    // too_deep: nesting beyond EXTRA_FLAGS_MAX_DEPTH means no nonce claimed.
    {
        std::string deep = "{\"deep\":";
        for (int i = 0; i < pow_v3::EXTRA_FLAGS_MAX_DEPTH + 1; ++i) deep += "{\"d\":";
        deep += "1";
        for (int i = 0; i < pow_v3::EXTRA_FLAGS_MAX_DEPTH + 1; ++i) deep += "}";
        deep += ",\"v3\":{\"admission_nonce\":\"" + nh + "\"}}";
        BOOST_CHECK(!pow_v3::extract_admission_nonce_hex(deep).has_value());
    }
}

BOOST_AUTO_TEST_CASE(carrier_merge_helper)
{
    const std::string& nh = VECTOR_NONCE_HEX;

    // Merge into empty produces the canonical carrier.
    BOOST_CHECK_EQUAL(pow_v3::merge_extra_flags_v3("", nh),
                      "{\"v3\":{\"admission_nonce\":\"" + nh + "\"}}");

    // Merge preserves existing top-level keys and the result round-trips
    // through the consensus extractor.
    const std::string merged = pow_v3::merge_extra_flags_v3(
        "{\"completion_id\":\"x\",\"proof_purpose\":\"audit\"}", nh);
    BOOST_CHECK(merged.find("completion_id") != std::string::npos);
    BOOST_CHECK(merged.find("proof_purpose") != std::string::npos);
    const auto got = pow_v3::extract_admission_nonce_hex(merged);
    BOOST_CHECK(got.has_value() && *got == nh);

    // Idempotent: re-merging replaces the v3 member instead of duplicating it
    // (a duplicate key would mean "no nonce claimed").
    const std::string remerged = pow_v3::merge_extra_flags_v3(merged, nh);
    const auto got2 = pow_v3::extract_admission_nonce_hex(remerged);
    BOOST_CHECK(got2.has_value() && *got2 == nh);

    // Invalid nonce shapes throw (producer-side error, never consensus).
    BOOST_CHECK_THROW(pow_v3::merge_extra_flags_v3("", std::string(63, 'a')), std::invalid_argument);
    BOOST_CHECK_THROW(pow_v3::merge_extra_flags_v3("", std::string(64, 'A')), std::invalid_argument);
}

// ---- §6 target derivation (vectors "target_derivation") -------------------

BOOST_AUTO_TEST_CASE(target_derivation_golden_vectors)
{
    struct Case {
        int64_t difficulty;
        uint64_t expected_tries;
        const char* target_hex_be; // big-endian, as in the vectors
    };
    // Goldens derive from the §1 calibration constants (ARGON_REF_US=4000,
    // DECODE_US_AT_NORMALIZER=6000000 -> 60 tries at normalizer). Regenerate
    // with: python -c "import pow_v3; [print(d, pow_v3.admission_expected_tries(d),
    // format((2**256-1)//pow_v3.admission_expected_tries(d), '064x')) for d in
    // (1,100000,500000,1000000,3000000)]" whenever the calibration changes.
    const Case cases[] = {
        {1, 60000000, "0000004795319ca1d36b941466302756cdb3c42ee02ef0f5e8969e842bbae082"},
        {100000, 600, "006d3a06d3a06d3a06d3a06d3a06d3a06d3a06d3a06d3a06d3a06d3a06d3a06d"},
        {500000, 120, "0222222222222222222222222222222222222222222222222222222222222222"},
        {1000000, 60, "0444444444444444444444444444444444444444444444444444444444444444"},
        {3000000, 20, "0ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"},
        {1000000000000LL, 1, "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"},
        {1000000000000000LL, 1, "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"},
    };
    for (const auto& c : cases) {
        BOOST_CHECK_EQUAL(pow_v3::admission_expected_tries(c.difficulty), c.expected_tries);
        const std::array<uint8_t, 32> target_le = pow_v3::admission_target_le(c.difficulty);
        // The vectors carry the target big-endian; the helper returns the
        // little-endian comparison domain — reverse for comparison.
        std::array<uint8_t, 32> target_be{};
        for (size_t i = 0; i < 32; ++i) target_be[i] = target_le[31 - i];
        BOOST_CHECK_MESSAGE(ToHex(target_be) == c.target_hex_be,
                            "difficulty " + std::to_string(c.difficulty) + ": " + ToHex(target_be));
    }

    BOOST_CHECK_THROW(pow_v3::admission_expected_tries(0), std::invalid_argument);
    BOOST_CHECK_THROW(pow_v3::admission_expected_tries(-5), std::invalid_argument);
}

BOOST_AUTO_TEST_CASE(admission_valid_strict_less_than_le)
{
    // uint256_le STRICT less-than (§6): equal is NOT valid; byte 31 is the
    // most significant.
    std::array<uint8_t, 32> a{};
    std::array<uint8_t, 32> b{};
    BOOST_CHECK(!pow_v3::admission_valid(a, b)); // equal (all zero)
    b[31] = 1;                                   // b = 2^248
    BOOST_CHECK(pow_v3::admission_valid(a, b));
    BOOST_CHECK(!pow_v3::admission_valid(b, a));
    a = b;
    BOOST_CHECK(!pow_v3::admission_valid(a, b)); // equal again
    a[0] = 1;                                    // a = 2^248 + 1 > b
    BOOST_CHECK(!pow_v3::admission_valid(a, b));
}

// ---- §4 B_cred credit units (R=1024 table, vectors "b_cred") ----------------

BOOST_AUTO_TEST_CASE(b_cred_golden_vectors)
{
    // Expected values are byte-identical to gen_v3_vectors.py (Python) — the
    // cross-language B_cred identity check. R units == 1 bit.
    // uniform_quarter_mass: mass ~ 0.25 each => 2 bits/step => 512 bits.
    {
        const std::vector<double> lo(256, 0.1);
        const std::vector<double> hi(256, 0.35 - 2 * pow_v3::ATOL);
        BOOST_CHECK_EQUAL(pow_v3::b_cred_units_from_bounds(lo, hi), 524288ULL);
    }
    // mixed_masses: lower[i] = i/1000, upper[i] = i/1000 + 0.001 + (i%7)/100.
    {
        std::vector<double> lo(256), hi(256);
        for (int i = 0; i < 256; ++i) {
            lo[i] = i / 1000.0;
            hi[i] = i / 1000.0 + 0.001 + (i % 7) / 100.0;
        }
        BOOST_CHECK_EQUAL(pow_v3::b_cred_units_from_bounds(lo, hi), 1489453ULL);
    }
    // point_bounds_atol_only: mass = 2*ATOL each => ~12.29 bits/step.
    {
        const std::vector<double> lo(256, 0.5);
        const std::vector<double> hi(256, 0.5);
        BOOST_CHECK_EQUAL(pow_v3::b_cred_units_from_bounds(lo, hi), 3220992ULL);
    }
    // full_mass_zero_bits: mass >= 1 contributes zero (never negative) units.
    {
        const std::vector<double> lo(256, 0.0);
        const std::vector<double> hi(256, 1.0);
        BOOST_CHECK_EQUAL(pow_v3::b_cred_units_from_bounds(lo, hi), 0ULL);
    }
    // §4 rejects: upper < lower, NaN/Inf, size mismatch — proof invalid.
    BOOST_CHECK_THROW(pow_v3::b_cred_units_from_bounds({0.5}, {0.4}), std::invalid_argument);
    BOOST_CHECK_THROW(pow_v3::b_cred_units_from_bounds({std::nan("")}, {0.5}), std::invalid_argument);
    BOOST_CHECK_THROW(pow_v3::b_cred_units_from_bounds({0.1, 0.2}, {0.5}), std::invalid_argument);
    // mass_q63 == 0 rejects (never awards max units); mass 1.0 credits 0.
    BOOST_CHECK_THROW(pow_v3::credit_units_for_step(0), std::invalid_argument);
    BOOST_CHECK_EQUAL(pow_v3::credit_units_for_step(pow_v3::mass_q63_for_step(0.0, 1.0)), 0ULL);
}

// ---- §4 table identity + boundary + conversion ------------------------------

// Little-endian SHA-256 of the compiled table must equal the checked-in
// identity (== the Python table's SHA), proving both languages share bytes.
static std::string bcred_table_le_sha256_hex()
{
    CSHA256 hasher;
    for (std::size_t n = 0; n < pow_v3::BCRED_TABLE_LEN; ++n) {
        uint8_t le[8];
        uint64_t v = pow_v3::BCRED_THRESHOLD_Q63[n];
        for (int b = 0; b < 8; ++b) le[b] = static_cast<uint8_t>((v >> (8 * b)) & 0xff);
        hasher.Write(le, 8);
    }
    unsigned char digest[CSHA256::OUTPUT_SIZE];
    hasher.Finalize(digest);
    const std::vector<unsigned char> d(digest, digest + CSHA256::OUTPUT_SIZE);
    return HexStr(d);
}

BOOST_AUTO_TEST_CASE(b_cred_table_identity_and_boundaries)
{
    // Table shape / anchors.
    BOOST_CHECK_EQUAL(pow_v3::BCRED_R, 1024U);
    BOOST_CHECK_EQUAL(pow_v3::BCRED_N_MAX, 32U * 1024U);
    BOOST_CHECK_EQUAL(pow_v3::BCRED_TABLE_LEN, 32U * 1024U + 1U);
    BOOST_CHECK_EQUAL(pow_v3::BCRED_THRESHOLD_Q63[0], pow_v3::BCRED_Q_ONE);        // 2^63
    BOOST_CHECK_EQUAL(pow_v3::BCRED_THRESHOLD_Q63[pow_v3::BCRED_N_MAX], 1ULL << 31); // 2^31
    // Non-increasing.
    for (std::size_t n = 1; n < pow_v3::BCRED_TABLE_LEN; ++n) {
        BOOST_CHECK(pow_v3::BCRED_THRESHOLD_Q63[n] <= pow_v3::BCRED_THRESHOLD_Q63[n - 1]);
    }
    // Cross-language table identity.
    BOOST_CHECK_EQUAL(bcred_table_le_sha256_hex(),
                      std::string(pow_v3::BCRED_TABLE_SHA256_HEX));

    // Boundary: mass_q63 == threshold[n] credits >= n; threshold[n]+1 credits < n.
    for (std::size_t n : {1U, 1024U, 5000U, 20000U, 32767U}) {
        const uint64_t t = pow_v3::BCRED_THRESHOLD_Q63[n];
        BOOST_CHECK(pow_v3::credit_units_for_step(t) >= n);
        if (t + 1 <= pow_v3::BCRED_Q_ONE) {
            BOOST_CHECK(pow_v3::credit_units_for_step(t + 1) < n);
        }
    }

    // Exact conversion anchors (integer arithmetic, no double*2^63).
    BOOST_CHECK_EQUAL(pow_v3::f64_to_q63_floor(1.0), pow_v3::BCRED_Q_ONE);
    BOOST_CHECK_EQUAL(pow_v3::f64_to_q63_ceil(1.0), pow_v3::BCRED_Q_ONE);
    BOOST_CHECK_EQUAL(pow_v3::f64_to_q63_floor(0.0), 0ULL);
    BOOST_CHECK_EQUAL(pow_v3::f64_to_q63_floor(0.5), 1ULL << 62);    // exact
    BOOST_CHECK_EQUAL(pow_v3::f64_to_q63_ceil(0.5), 1ULL << 62);
    BOOST_CHECK_EQUAL(pow_v3::ATOL_Q63_CEIL, 922337203685478ULL);
    // For x >= 2^-11, x*2^63 is an exact integer (ceil == floor). Only a value
    // with a bit below 2^-63 yields ceil == floor + 1.
    BOOST_CHECK_EQUAL(pow_v3::f64_to_q63_ceil(0.1), pow_v3::f64_to_q63_floor(0.1));
    const double frac = std::ldexp(0.1, -10);  // 9.765625e-05: sub-2^-63 bit
    BOOST_CHECK_EQUAL(pow_v3::f64_to_q63_ceil(frac),
                      pow_v3::f64_to_q63_floor(frac) + 1);
}

// ---- §5 tier rule -----------------------------------------------------------

BOOST_AUTO_TEST_CASE(tier_rule_boundaries)
{
    using pow_v3::Tier;
    const uint64_t floor_units = pow_v3::B_FLOOR_UNITS;   // 45 * R
    const uint64_t free_units = pow_v3::B_FREE_UNITS;     // 70 * R
    BOOST_CHECK_EQUAL(floor_units, 45ULL * 1024ULL);
    BOOST_CHECK_EQUAL(free_units, 70ULL * 1024ULL);
    BOOST_CHECK(pow_v3::tier_for_b_cred_units(0) == Tier::Invalid);
    BOOST_CHECK(pow_v3::tier_for_b_cred_units(floor_units - 1) == Tier::Invalid);
    BOOST_CHECK(pow_v3::tier_for_b_cred_units(floor_units) == Tier::AdmissionRequired);
    BOOST_CHECK(pow_v3::tier_for_b_cred_units(free_units - 1) == Tier::AdmissionRequired);
    BOOST_CHECK(pow_v3::tier_for_b_cred_units(free_units) == Tier::Free);
    BOOST_CHECK_EQUAL(std::string{pow_v3::tier_name(Tier::Invalid)}, "invalid");
    BOOST_CHECK_EQUAL(std::string{pow_v3::tier_name(Tier::AdmissionRequired)}, "admission_required");
    BOOST_CHECK_EQUAL(std::string{pow_v3::tier_name(Tier::Free)}, "free");
}

// ---- §6 prompt commitment (vectors "admission", SHA-256 only) --------------

BOOST_AUTO_TEST_CASE(prompt_commitment_golden_vectors)
{
    // ref_model / other_nonce / empty_model_id share the same prefix commitment.
    {
        const std::vector<int64_t> prompt{1, 2, 3};
        const std::vector<uint8_t> mask{0, 0, 1};
        BOOST_CHECK_EQUAL(ToHex(pow_v3::prompt_commitment(prompt, mask)),
                          "f0f06eb27e5b639a92035c2f291fb6c1b4062f238b3e1ded864391faca11a0e3");
    }
    // long_prefix_beyond_window: 399 tokens, all-false mask — the commitment
    // covers the FULL pre-window prefix, not just the rolling 256 (§6).
    {
        const std::vector<int64_t> prompt = Iota64(1, 399);
        const std::vector<uint8_t> mask(399, 0);
        BOOST_CHECK_EQUAL(ToHex(pow_v3::prompt_commitment(prompt, mask)),
                          "be07eae36198aa8783f85a243ac10eda6913788ce0d2a69d897376a2e563281b");
    }
    // empty_prefix
    {
        BOOST_CHECK_EQUAL(ToHex(pow_v3::prompt_commitment({}, {})),
                          "895dfbaed4dbc7e2554ae49cb7045129bba1daa616ec313d5ab603598f48334f");
    }
    // Canonical shape: one mask entry per prompt token (§6).
    BOOST_CHECK_THROW(pow_v3::prompt_commitment({1, 2, 3}, {0, 0}), std::invalid_argument);
}

// ---- §6 Argon2id admission digests (vectors "admission") --------------------
// Only run when the build links libargon2 (POW_V3_HAVE_ARGON2); the bcore
// build requires it, but keep the guard so the file stays portable.

#ifdef POW_V3_HAVE_ARGON2
BOOST_AUTO_TEST_CASE(admission_digest_golden_vectors)
{
    // msg_w = build_step_message(HEADER, VDF, 7, 0, [1,2,3], "fp16") — the
    // window-first-step message WITHOUT the nonce (§6).
    const std::vector<uint8_t> msg_w = pow_v3::build_step_message(
        VectorHeader(), VectorVdf(), 7, 0, {1, 2, 3}, "fp16");
    BOOST_REQUIRE_EQUAL(ToHex(pow_v3::step_digest(msg_w)),
                        "55f878f9395d035483de42ab173acf1943816ee9377853a6046df654377c1e52");

    const auto nonce = VectorNonce();
    const std::array<uint8_t, 32> zero_nonce{};
    const std::array<uint8_t, 32> commitment =
        pow_v3::prompt_commitment({1, 2, 3}, {0, 0, 1});

    struct Case {
        const char* name;
        std::string model_identifier;
        const uint8_t* nonce;
        size_t message_len;
        const char* digest_hex;
    };
    const Case cases[] = {
        {"ref_model", "org/model@abcdef012345", nonce.data(), 2256,
         "1bcae331636ae99745b366e68273ba0f9d67e923f08f2c35ac980f71f656d909"},
        {"empty_model_id", "", nonce.data(), 2234,
         "64024573723aa1e93aec3ac9f5a515327f3c055dd979a5db1214dcc4dd382183"},
        {"other_nonce", "org/model@abcdef012345", zero_nonce.data(), 2256,
         "6da9fe435c597094e8d4fb1b94b67d26b6abb9351fb7efcce81ef0a3a896540d"},
    };
    for (const auto& c : cases) {
        const std::vector<uint8_t> msg =
            pow_v3::admission_message(msg_w, c.model_identifier, c.nonce, commitment);
        BOOST_CHECK_EQUAL(msg.size(), c.message_len);
        BOOST_CHECK_MESSAGE(ToHex(pow_v3::argon2id_digest(msg)) == c.digest_hex,
                            std::string("admission ") + c.name + ": digest mismatch");
    }

    // long_prefix_beyond_window / empty_prefix vary only the commitment.
    {
        const auto commit_long = pow_v3::prompt_commitment(Iota64(1, 399), std::vector<uint8_t>(399, 0));
        const auto msg = pow_v3::admission_message(msg_w, "org/model@abcdef012345", nonce.data(), commit_long);
        BOOST_CHECK_EQUAL(ToHex(pow_v3::argon2id_digest(msg)),
                          "68ab7a7fa899fa990df677896310358a224a8cc174f5feca9d8b524980d0e4ee");
    }
    {
        const auto commit_empty = pow_v3::prompt_commitment({}, {});
        const auto msg = pow_v3::admission_message(msg_w, "org/model@abcdef012345", nonce.data(), commit_empty);
        BOOST_CHECK_EQUAL(ToHex(pow_v3::argon2id_digest(msg)),
                          "cbb0053d265b515f754347a112c6a62304e07c314a8f7186912f8c2b4a982ec7");
    }
}
#endif // POW_V3_HAVE_ARGON2

BOOST_AUTO_TEST_SUITE_END()
