// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_BLOCKHEADER_PROOF_H_
#define FLATBUFFERS_GENERATED_BLOCKHEADER_PROOF_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "proof_generated.h"

namespace proof {

struct BlockHeader;
struct BlockHeaderBuilder;

struct MiningResponse;
struct MiningResponseBuilder;

struct BlockHeader FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BlockHeaderBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REQ_ID = 4,
    VT_VERSION = 6,
    VT_PREV_BLOCK_HASH = 8,
    VT_MERKLE_ROOT = 10,
    VT_TIMESTAMP = 12,
    VT_BITS = 14
  };
  uint32_t req_id() const {
    return GetField<uint32_t>(VT_REQ_ID, 0);
  }
  uint32_t version() const {
    return GetField<uint32_t>(VT_VERSION, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *prev_block_hash() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_PREV_BLOCK_HASH);
  }
  const ::flatbuffers::Vector<uint8_t> *merkle_root() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_MERKLE_ROOT);
  }
  uint32_t timestamp() const {
    return GetField<uint32_t>(VT_TIMESTAMP, 0);
  }
  uint32_t bits() const {
    return GetField<uint32_t>(VT_BITS, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_REQ_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyOffset(verifier, VT_PREV_BLOCK_HASH) &&
           verifier.VerifyVector(prev_block_hash()) &&
           VerifyOffset(verifier, VT_MERKLE_ROOT) &&
           verifier.VerifyVector(merkle_root()) &&
           VerifyField<uint32_t>(verifier, VT_TIMESTAMP, 4) &&
           VerifyField<uint32_t>(verifier, VT_BITS, 4) &&
           verifier.EndTable();
  }
};

struct BlockHeaderBuilder {
  typedef BlockHeader Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_req_id(uint32_t req_id) {
    fbb_.AddElement<uint32_t>(BlockHeader::VT_REQ_ID, req_id, 0);
  }
  void add_version(uint32_t version) {
    fbb_.AddElement<uint32_t>(BlockHeader::VT_VERSION, version, 0);
  }
  void add_prev_block_hash(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> prev_block_hash) {
    fbb_.AddOffset(BlockHeader::VT_PREV_BLOCK_HASH, prev_block_hash);
  }
  void add_merkle_root(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> merkle_root) {
    fbb_.AddOffset(BlockHeader::VT_MERKLE_ROOT, merkle_root);
  }
  void add_timestamp(uint32_t timestamp) {
    fbb_.AddElement<uint32_t>(BlockHeader::VT_TIMESTAMP, timestamp, 0);
  }
  void add_bits(uint32_t bits) {
    fbb_.AddElement<uint32_t>(BlockHeader::VT_BITS, bits, 0);
  }
  explicit BlockHeaderBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BlockHeader> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BlockHeader>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BlockHeader> CreateBlockHeader(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t req_id = 0,
    uint32_t version = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> prev_block_hash = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> merkle_root = 0,
    uint32_t timestamp = 0,
    uint32_t bits = 0) {
  BlockHeaderBuilder builder_(_fbb);
  builder_.add_bits(bits);
  builder_.add_timestamp(timestamp);
  builder_.add_merkle_root(merkle_root);
  builder_.add_prev_block_hash(prev_block_hash);
  builder_.add_version(version);
  builder_.add_req_id(req_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BlockHeader> CreateBlockHeaderDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t req_id = 0,
    uint32_t version = 0,
    const std::vector<uint8_t> *prev_block_hash = nullptr,
    const std::vector<uint8_t> *merkle_root = nullptr,
    uint32_t timestamp = 0,
    uint32_t bits = 0) {
  auto prev_block_hash__ = prev_block_hash ? _fbb.CreateVector<uint8_t>(*prev_block_hash) : 0;
  auto merkle_root__ = merkle_root ? _fbb.CreateVector<uint8_t>(*merkle_root) : 0;
  return proof::CreateBlockHeader(
      _fbb,
      req_id,
      version,
      prev_block_hash__,
      merkle_root__,
      timestamp,
      bits);
}

struct MiningResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MiningResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_REQ_ID = 4,
    VT_NONCE = 6,
    VT_ADJUSTED_BITS = 8,
    VT_POW_BLOB_HASH = 10,
    VT_DIFFICULTY = 12,
    VT_POW_BLOB = 14,
    VT_COMPLETION_ID = 16
  };
  uint32_t req_id() const {
    return GetField<uint32_t>(VT_REQ_ID, 0);
  }
  uint32_t nonce() const {
    return GetField<uint32_t>(VT_NONCE, 0);
  }
  uint32_t adjusted_bits() const {
    return GetField<uint32_t>(VT_ADJUSTED_BITS, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *pow_blob_hash() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_POW_BLOB_HASH);
  }
  uint32_t difficulty() const {
    return GetField<uint32_t>(VT_DIFFICULTY, 0);
  }
  const proof::Proof *pow_blob() const {
    return GetPointer<const proof::Proof *>(VT_POW_BLOB);
  }
  const ::flatbuffers::String *completion_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COMPLETION_ID);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_REQ_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_NONCE, 4) &&
           VerifyField<uint32_t>(verifier, VT_ADJUSTED_BITS, 4) &&
           VerifyOffset(verifier, VT_POW_BLOB_HASH) &&
           verifier.VerifyVector(pow_blob_hash()) &&
           VerifyField<uint32_t>(verifier, VT_DIFFICULTY, 4) &&
           VerifyOffset(verifier, VT_POW_BLOB) &&
           verifier.VerifyTable(pow_blob()) &&
           VerifyOffset(verifier, VT_COMPLETION_ID) &&
           verifier.VerifyString(completion_id()) &&
           verifier.EndTable();
  }
};

struct MiningResponseBuilder {
  typedef MiningResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_req_id(uint32_t req_id) {
    fbb_.AddElement<uint32_t>(MiningResponse::VT_REQ_ID, req_id, 0);
  }
  void add_nonce(uint32_t nonce) {
    fbb_.AddElement<uint32_t>(MiningResponse::VT_NONCE, nonce, 0);
  }
  void add_adjusted_bits(uint32_t adjusted_bits) {
    fbb_.AddElement<uint32_t>(MiningResponse::VT_ADJUSTED_BITS, adjusted_bits, 0);
  }
  void add_pow_blob_hash(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> pow_blob_hash) {
    fbb_.AddOffset(MiningResponse::VT_POW_BLOB_HASH, pow_blob_hash);
  }
  void add_difficulty(uint32_t difficulty) {
    fbb_.AddElement<uint32_t>(MiningResponse::VT_DIFFICULTY, difficulty, 0);
  }
  void add_pow_blob(::flatbuffers::Offset<proof::Proof> pow_blob) {
    fbb_.AddOffset(MiningResponse::VT_POW_BLOB, pow_blob);
  }
  void add_completion_id(::flatbuffers::Offset<::flatbuffers::String> completion_id) {
    fbb_.AddOffset(MiningResponse::VT_COMPLETION_ID, completion_id);
  }
  explicit MiningResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MiningResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MiningResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MiningResponse> CreateMiningResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t req_id = 0,
    uint32_t nonce = 0,
    uint32_t adjusted_bits = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> pow_blob_hash = 0,
    uint32_t difficulty = 0,
    ::flatbuffers::Offset<proof::Proof> pow_blob = 0,
    ::flatbuffers::Offset<::flatbuffers::String> completion_id = 0) {
  MiningResponseBuilder builder_(_fbb);
  builder_.add_completion_id(completion_id);
  builder_.add_pow_blob(pow_blob);
  builder_.add_difficulty(difficulty);
  builder_.add_pow_blob_hash(pow_blob_hash);
  builder_.add_adjusted_bits(adjusted_bits);
  builder_.add_nonce(nonce);
  builder_.add_req_id(req_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MiningResponse> CreateMiningResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t req_id = 0,
    uint32_t nonce = 0,
    uint32_t adjusted_bits = 0,
    const std::vector<uint8_t> *pow_blob_hash = nullptr,
    uint32_t difficulty = 0,
    ::flatbuffers::Offset<proof::Proof> pow_blob = 0,
    const char *completion_id = nullptr) {
  auto pow_blob_hash__ = pow_blob_hash ? _fbb.CreateVector<uint8_t>(*pow_blob_hash) : 0;
  auto completion_id__ = completion_id ? _fbb.CreateString(completion_id) : 0;
  return proof::CreateMiningResponse(
      _fbb,
      req_id,
      nonce,
      adjusted_bits,
      pow_blob_hash__,
      difficulty,
      pow_blob,
      completion_id__);
}

inline const proof::BlockHeader *GetBlockHeader(const void *buf) {
  return ::flatbuffers::GetRoot<proof::BlockHeader>(buf);
}

inline const proof::BlockHeader *GetSizePrefixedBlockHeader(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<proof::BlockHeader>(buf);
}

inline bool VerifyBlockHeaderBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<proof::BlockHeader>(nullptr);
}

inline bool VerifySizePrefixedBlockHeaderBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<proof::BlockHeader>(nullptr);
}

inline void FinishBlockHeaderBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<proof::BlockHeader> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedBlockHeaderBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<proof::BlockHeader> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace proof

#endif  // FLATBUFFERS_GENERATED_BLOCKHEADER_PROOF_H_
