// Copyright (c) 2010 Satoshi Nakamoto
// Copyright (c) 2009-2022 The Bitcoin Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#include <common/args.h>
#include <rpc/client.h>
#include <tinyformat.h>

#include <set>
#include <stdint.h>
#include <string>
#include <string_view>

class CRPCConvertParam
{
public:
    std::string methodName; //!< method whose params want conversion
    int paramIdx;           //!< 0-based idx of param to convert
    std::string paramName;  //!< parameter name
};

// clang-format off
/**
 * Specify a (method, idx, name) here if the argument is a non-string RPC
 * argument and needs to be converted from JSON.
 *
 * @note Parameter indexes start from 0.
 */
static const CRPCConvertParam vRPCConvertParams[] =
{
    { "setmocktime", 0, "timestamp" },
    { "mockscheduler", 0, "delta_time" },
    { "utxoupdatepsbt", 1, "descriptors" },
    { "generatetoaddress", 0, "nblocks" },
    { "generatetoaddress", 2, "maxtries" },
    { "generatetodescriptor", 0, "num_blocks" },
    { "generatetodescriptor", 2, "maxtries" },
    { "generateblock", 1, "transactions" },
    { "generateblock", 2, "submit" },
    { "getnetworkhashps", 0, "nblocks" },
    { "getnetworkhashps", 1, "height" },
    { "sendtoaddress", 1, "amount" },
    { "sendtoaddress", 4, "subtractfeefromamount" },
    { "sendtoaddress", 5 , "replaceable" },
    { "sendtoaddress", 6 , "conf_target" },
    { "sendtoaddress", 8, "avoid_reuse" },
    { "sendtoaddress", 9, "fee_rate"},
    { "sendtoaddress", 10, "verbose"},
    { "settxfee", 0, "amount" },
    { "getreceivedbyaddress", 1, "minconf" },
    { "getreceivedbyaddress", 2, "include_immature_coinbase" },
    { "getreceivedbylabel", 1, "minconf" },
    { "getreceivedbylabel", 2, "include_immature_coinbase" },
    { "listreceivedbyaddress", 0, "minconf" },
    { "listreceivedbyaddress", 1, "include_empty" },
    { "listreceivedbyaddress", 2, "include_watchonly" },
    { "listreceivedbyaddress", 4, "include_immature_coinbase" },
    { "listreceivedbylabel", 0, "minconf" },
    { "listreceivedbylabel", 1, "include_empty" },
    { "listreceivedbylabel", 2, "include_watchonly" },
    { "listreceivedbylabel", 3, "include_immature_coinbase" },
    { "getbalance", 1, "minconf" },
    { "getbalance", 2, "include_watchonly" },
    { "getbalance", 3, "avoid_reuse" },
    { "getblockfrompeer", 1, "peer_id" },
    { "getblockhash", 0, "height" },
    { "waitforblockheight", 0, "height" },
    { "waitforblockheight", 1, "timeout" },
    { "waitforblock", 1, "timeout" },
    { "waitfornewblock", 0, "timeout" },
    { "listtransactions", 1, "count" },
    { "listtransactions", 2, "skip" },
    { "listtransactions", 3, "include_watchonly" },
    { "walletpassphrase", 1, "timeout" },
    { "getblocktemplate", 0, "template_request" },
    { "submit_mining_response", 0, "req_id" },
    { "release_mining_work_unit", 0, "req_id" },
    { "listsinceblock", 1, "target_confirmations" },
    { "listsinceblock", 2, "include_watchonly" },
    { "listsinceblock", 3, "include_removed" },
    { "listsinceblock", 4, "include_change" },
    { "sendmany", 1, "amounts" },
    { "sendmany", 2, "minconf" },
    { "sendmany", 4, "subtractfeefrom" },
    { "sendmany", 5 , "replaceable" },
    { "sendmany", 6 , "conf_target" },
    { "sendmany", 8, "fee_rate"},
    { "sendmany", 9, "verbose" },
    { "deriveaddresses", 1, "range" },
    { "scanblocks", 1, "scanobjects" },
    { "scanblocks", 2, "start_height" },
    { "scanblocks", 3, "stop_height" },
    { "scanblocks", 5, "options" },
    { "scanblocks", 5, "filter_false_positives" },
    { "getdescriptoractivity", 0, "blockhashes" },
    { "getdescriptoractivity", 1, "scanobjects" },
    { "getdescriptoractivity", 2, "include_mempool" },
    { "scantxoutset", 1, "scanobjects" },
    { "createmultisig", 0, "nrequired" },
    { "createmultisig", 1, "keys" },
    { "listunspent", 0, "minconf" },
    { "listunspent", 1, "maxconf" },
    { "listunspent", 2, "addresses" },
    { "listunspent", 3, "include_unsafe" },
    { "listunspent", 4, "query_options" },
    { "listunspent", 4, "minimumAmount" },
    { "listunspent", 4, "maximumAmount" },
    { "listunspent", 4, "maximumCount" },
    { "listunspent", 4, "minimumSumAmount" },
    { "listunspent", 4, "include_immature_coinbase" },
    { "getblock", 1, "verbosity" },
    { "getblock", 1, "verbose" },
    { "getblockheader", 1, "verbose" },
    { "getchaintxstats", 0, "nblocks" },
    { "gettransaction", 1, "include_watchonly" },
    { "gettransaction", 2, "verbose" },
    { "getrawtransaction", 1, "verbosity" },
    { "getrawtransaction", 1, "verbose" },
    { "createrawtransaction", 0, "inputs" },
    { "createrawtransaction", 1, "outputs" },
    { "createrawtransaction", 2, "locktime" },
    { "createrawtransaction", 3, "replaceable" },
    { "createassettransaction", 0, "inputs" },
    { "createassettransaction", 1, "outputs" },
    { "createassettransaction", 2, "locktime" },
    { "transferasset", 0, "inputs" },
    { "transferasset", 1, "outputs" },
    { "transferasset", 3, "btc_amounts" },
    { "sendasset", 2, "amount" },
    { "sendasset", 3, "options" },
    { "listassets", 0, "include_unregistered" },
    { "listassets", 1, "verbose" },
    { "listassets", 2, "filter" },
    { "listregisteredassets", 0, "verbose" },
    { "listassetutxos", 0, "assets" },
    { "listassetutxos", 1, "minconf" },
    { "listassetutxos", 2, "maxconf" },
    { "getassetbalance", 0, "assets" },
    { "validateassetconservation", 1, "resolve_tickers" },
    { "decodeassettransaction", 1, "resolve_tickers" },
    { "decoderawtransaction", 1, "iswitness" },
    { "signrawtransactionwithkey", 1, "privkeys" },
    { "signrawtransactionwithkey", 2, "prevtxs" },
    { "signrawtransactionwithwallet", 1, "prevtxs" },
    { "sendrawtransaction", 1, "maxfeerate" },
    { "sendrawtransaction", 2, "maxburnamount" },
    { "testmempoolaccept", 0, "rawtxs" },
    { "testmempoolaccept", 1, "maxfeerate" },
    { "submitpackage", 0, "package" },
    { "submitpackage", 1, "maxfeerate" },
    { "submitpackage", 2, "maxburnamount" },
    { "combinerawtransaction", 0, "txs" },
    { "fundrawtransaction", 1, "options" },
    { "fundrawtransaction", 1, "add_inputs"},
    { "fundrawtransaction", 1, "include_unsafe"},
    { "fundrawtransaction", 1, "minconf"},
    { "fundrawtransaction", 1, "maxconf"},
    { "fundrawtransaction", 1, "changePosition"},
    { "fundrawtransaction", 1, "includeWatching"},
    { "fundrawtransaction", 1, "lockUnspents"},
    { "fundrawtransaction", 1, "fee_rate"},
    { "fundrawtransaction", 1, "feeRate"},
    { "fundrawtransaction", 1, "subtractFeeFromOutputs"},
    { "fundrawtransaction", 1, "input_weights"},
    { "fundrawtransaction", 1, "conf_target"},
    { "fundrawtransaction", 1, "replaceable"},
    { "fundrawtransaction", 1, "solving_data"},
    { "fundrawtransaction", 1, "max_tx_weight"},
    { "fundrawtransaction", 2, "iswitness" },
    { "walletcreatefundedpsbt", 0, "inputs" },
    { "walletcreatefundedpsbt", 1, "outputs" },
    { "walletcreatefundedpsbt", 2, "locktime" },
    { "walletcreatefundedpsbt", 3, "options" },
    { "walletcreatefundedpsbt", 3, "add_inputs"},
    { "walletcreatefundedpsbt", 3, "include_unsafe"},
    { "walletcreatefundedpsbt", 3, "minconf"},
    { "walletcreatefundedpsbt", 3, "maxconf"},
    { "walletcreatefundedpsbt", 3, "changePosition"},
    { "walletcreatefundedpsbt", 3, "includeWatching"},
    { "walletcreatefundedpsbt", 3, "lockUnspents"},
    { "walletcreatefundedpsbt", 3, "fee_rate"},
    { "walletcreatefundedpsbt", 3, "feeRate"},
    { "walletcreatefundedpsbt", 3, "subtractFeeFromOutputs"},
    { "walletcreatefundedpsbt", 3, "conf_target"},
    { "walletcreatefundedpsbt", 3, "replaceable"},
    { "walletcreatefundedpsbt", 3, "solving_data"},
    { "walletcreatefundedpsbt", 3, "max_tx_weight"},
    { "walletcreatefundedpsbt", 4, "bip32derivs" },
    { "walletprocesspsbt", 1, "sign" },
    { "walletprocesspsbt", 3, "bip32derivs" },
    { "walletprocesspsbt", 4, "finalize" },
    { "descriptorprocesspsbt", 1, "descriptors"},
    { "descriptorprocesspsbt", 3, "bip32derivs" },
    { "descriptorprocesspsbt", 4, "finalize" },
    { "createpsbt", 0, "inputs" },
    { "createpsbt", 1, "outputs" },
    { "createpsbt", 2, "locktime" },
    { "createpsbt", 3, "replaceable" },
    { "combinepsbt", 0, "txs"},
    { "joinpsbts", 0, "txs"},
    { "finalizepsbt", 1, "extract"},
    { "converttopsbt", 1, "permitsigdata"},
    { "converttopsbt", 2, "iswitness"},
    { "gettxout", 1, "n" },
    { "gettxout", 2, "include_mempool" },
    { "gettxoutproof", 0, "txids" },
    { "gettxoutsetinfo", 1, "hash_or_height" },
    { "gettxoutsetinfo", 2, "use_index"},
    { "dumptxoutset", 2, "options" },
    { "dumptxoutset", 2, "rollback" },
    { "lockunspent", 0, "unlock" },
    { "lockunspent", 1, "transactions" },
    { "lockunspent", 2, "persistent" },
    { "send", 0, "outputs" },
    { "send", 1, "conf_target" },
    { "send", 3, "fee_rate"},
    { "send", 4, "options" },
    { "send", 4, "add_inputs"},
    { "send", 4, "include_unsafe"},
    { "send", 4, "minconf"},
    { "send", 4, "maxconf"},
    { "send", 4, "add_to_wallet"},
    { "send", 4, "change_position"},
    { "send", 4, "fee_rate"},
    { "send", 4, "include_watching"},
    { "send", 4, "inputs"},
    { "send", 4, "locktime"},
    { "send", 4, "lock_unspents"},
    { "send", 4, "psbt"},
    { "send", 4, "subtract_fee_from_outputs"},
    { "send", 4, "conf_target"},
    { "send", 4, "replaceable"},
    { "send", 4, "solving_data"},
    { "send", 4, "max_tx_weight"},
    { "sendall", 0, "recipients" },
    { "sendall", 1, "conf_target" },
    { "sendall", 3, "fee_rate"},
    { "sendall", 4, "options" },
    { "sendall", 4, "add_to_wallet"},
    { "sendall", 4, "fee_rate"},
    { "sendall", 4, "include_watching"},
    { "sendall", 4, "inputs"},
    { "sendall", 4, "locktime"},
    { "sendall", 4, "lock_unspents"},
    { "sendall", 4, "psbt"},
    { "sendall", 4, "send_max"},
    { "sendall", 4, "minconf"},
    { "sendall", 4, "maxconf"},
    { "sendall", 4, "conf_target"},
    { "sendall", 4, "replaceable"},
    { "sendall", 4, "solving_data"},
    { "simulaterawtransaction", 0, "rawtxs" },
    { "simulaterawtransaction", 1, "options" },
    { "simulaterawtransaction", 1, "include_watchonly"},
    { "importmempool", 1, "options" },
    { "importmempool", 1, "apply_fee_delta_priority" },
    { "importmempool", 1, "use_current_time" },
    { "importmempool", 1, "apply_unbroadcast_set" },
    { "importdescriptors", 0, "requests" },
    { "listdescriptors", 0, "private" },
    { "verifychain", 0, "checklevel" },
    { "verifychain", 1, "nblocks" },
    { "getreorgadvisories", 0, "count" },
    { "getblockstats", 0, "hash_or_height" },
    { "getblockstats", 1, "stats" },
    { "getspvtickinfo", 0, "height" },
    { "submitreorgdecision", 1, "gate_id" },
    { "submitreorgdecision", 2, "invalidate" },
    { "clearreorgveto", 0, "gate_id" },
    { "pruneblockchain", 0, "height" },
    { "keypoolrefill", 0, "newsize" },
    { "getrawmempool", 0, "verbose" },
    { "getrawmempool", 1, "mempool_sequence" },
    { "getorphantxs", 0, "verbosity" },
    { "estimatesmartfee", 0, "conf_target" },
    { "estimaterawfee", 0, "conf_target" },
    { "estimaterawfee", 1, "threshold" },
    { "revalidateblock", 1, "timeout_ms" },
    { "prioritisetransaction", 1, "dummy" },
    { "prioritisetransaction", 2, "fee_delta" },
    { "setban", 2, "bantime" },
    { "setban", 3, "absolute" },
    { "setnetworkactive", 0, "state" },
    { "setwalletflag", 1, "value" },
    { "getmempoolancestors", 1, "verbose" },
    { "getmempooldescendants", 1, "verbose" },
    { "gettxspendingprevout", 0, "outputs" },
    { "bumpfee", 1, "options" },
    { "bumpfee", 1, "conf_target"},
    { "bumpfee", 1, "fee_rate"},
    { "bumpfee", 1, "replaceable"},
    { "bumpfee", 1, "outputs"},
    { "bumpfee", 1, "original_change_index"},
    { "psbtbumpfee", 1, "options" },
    { "psbtbumpfee", 1, "conf_target"},
    { "psbtbumpfee", 1, "fee_rate"},
    { "psbtbumpfee", 1, "replaceable"},
    { "psbtbumpfee", 1, "outputs"},
    { "psbtbumpfee", 1, "original_change_index"},
    { "logging", 0, "include" },
    { "logging", 1, "exclude" },
    { "disconnectnode", 1, "nodeid" },
    { "upgradewallet", 0, "version" },
    { "gethdkeys", 0, "active_only" },
    { "gethdkeys", 0, "options" },
    { "gethdkeys", 0, "private" },
    { "createwalletdescriptor", 1, "options" },
    { "createwalletdescriptor", 1, "internal" },
    // Echo with conversion (For testing only)
    { "echojson", 0, "arg0" },
    { "echojson", 1, "arg1" },
    { "echojson", 2, "arg2" },
    { "echojson", 3, "arg3" },
    { "echojson", 4, "arg4" },
    { "echojson", 5, "arg5" },
    { "echojson", 6, "arg6" },
    { "echojson", 7, "arg7" },
    { "echojson", 8, "arg8" },
    { "echojson", 9, "arg9" },
    { "rescanblockchain", 0, "start_height"},
    { "rescanblockchain", 1, "stop_height"},
    { "createwallet", 1, "disable_private_keys"},
    { "createwallet", 2, "blank"},
    { "createwallet", 4, "avoid_reuse"},
    { "createwallet", 5, "descriptors"},
    { "createwallet", 6, "load_on_startup"},
    { "createwallet", 7, "external_signer"},
    { "restorewallet", 2, "load_on_startup"},
    { "loadwallet", 1, "load_on_startup"},
    { "unloadwallet", 1, "load_on_startup"},
    { "getnodeaddresses", 0, "count"},
    { "addpeeraddress", 1, "port"},
    { "addpeeraddress", 2, "tried"},
    { "sendmsgtopeer", 0, "peer_id" },
    { "stop", 0, "wait" },
    { "addnode", 2, "v2transport" },
    { "addconnection", 2, "v2transport" },
    { "createmodeldeposit", 2, "difficulty_multiplier" },
    { "createmodelcommit", 1, "deposit_vout" },
    { "createmodelcommit", 2, "tx_count" },
    { "createmodelcommit", 3, "funding_utxos" },
    { "splitutxo", 1, "vout" },
    { "splitutxo", 2, "count" },
    { "splitutxo", 3, "target_amount_sat" },
    { "cosign.discussion_scopes", 0, "since" },
    { "cosign.discussion_scopes", 1, "limit" },
    { "cosign.discussion_scopes", 2, "force_refresh" },
    { "cosign.discussion_scopes", 3, "only_live_verified" },
    { "createchallengecommits", 1, "tx_count" },
    { "createchallengecommits", 2, "funding_utxos" },
    { "createmodelburn", 1, "broadcast" },
    { "createmodelreclaim", 1, "broadcast" },
    { "getmodelslist", 0, "short_view" },
    { "getrecentvalidations", 0, "count" },
    { "setminermodel", 1, "clear" },
    { "getassetpolicy", 1, "include_history" },
    // TensorCash: raw transaction output extensions
    { "rawtxattachissuerreg", 1, "vout" },
    { "rawtxattachissuerreg", 3, "policy_bits" },
    { "rawtxattachissuerreg", 4, "allowed_spk_families" },
    { "rawtxattachissuerreg", 5, "unlock_fees_sats" },
    { "rawtxattachissuerreg", 7, "decimals" },
    { "rawtxattachassettag", 1, "vout" },
    { "rawtxattachassettag", 3, "amount" },
    { "rawtxattachassettag", 4, "flags" },
    // TensorCash: asset RPC methods
    { "rawtxaddoutext", 1, "vout" },
    { "registerasset", 1, "amount" },
    { "registerasset", 3, "policy_bits" },
    { "registerasset", 4, "allowed_spk_families" },
    { "registerasset", 5, "unlock_fees_sats" },
    { "registerasset", 7, "decimals" },
    { "registerasset", 8, "options" },
    { "sponsorchildasset", 4, "options" },
    { "listassetcomplianceroots", 1, "count" },
    { "updatecomplianceroot", 2, "options" },
    { "asset.build_delivery_template", 2, "amount" },
    { "asset.build_delivery_template", 3, "options" },
    { "mintasset", 1, "icu_vout" },
    { "mintasset", 3, "icu_amount" },
    { "mintasset", 5, "asset_amount_btc" },
    { "mintasset", 7, "asset_units" },
    { "mintasset", 8, "policy_bits" },
    { "mintasset", 9, "allowed_spk_families" },
    { "mintasset", 10, "unlock_fees_sats" },
    { "mintasset", 11, "options" },
    { "burnasset", 1, "icu_vout" },
    { "burnasset", 3, "asset_vout" },
    { "burnasset", 5, "icu_amount" },
    { "burnasset", 7, "policy_bits" },
    { "burnasset", 8, "allowed_spk_families" },
    { "burnasset", 9, "unlock_fees_sats" },
    { "burnasset", 10, "options" },
    // TensorCash: scalar feed RPC methods (CFD_GENERALISATION.md §3) — numeric/object args need
    // client-side JSON conversion so the bitcoin-cli path parses them as values, not strings.
    { "scalarpublish_raw", 1, "icu_vout" },
    { "scalarpublish_raw", 4, "new_icu_amount" },
    { "scalarpublish_raw", 5, "feed_id" },
    { "scalarpublish_raw", 6, "scalar_epoch" },
    { "scalarpublish_raw", 8, "scalar_format_id" },
    { "scalarpublish_raw", 9, "options" },
    { "scalargetfeed", 1, "feed_id" },
    { "scalargetfeed", 2, "epoch" },
    // TensorCash: repo contract RPC methods
    { "repo.propose", 0, "terms" },
    { "repo.accept", 1, "options" },
    { "repo.import_offer", 0, "offer" },
    { "repo.import_acceptance", 0, "acceptance" },
    { "repo.import_repay_address", 0, "payload" },
    { "repo.build_open", 1, "options" },
    { "repo.build_repay_release", 1, "options" },
    { "repo.build_default_sweep", 1, "options" },
    { "spot.propose", 0, "params" },
    { "spot.import_offer", 0, "offer" },
    { "spot.accept", 1, "options" },
    { "spot.import_acceptance", 1, "acceptance" },
    { "spot.build_atomic", 1, "options" },
    { "adaptor.complete", 1, "secrets" },
    { "adaptor.complete", 2, "peer_commitments" },
    { "musig.keyagg", 0, "pubkeys" },
    { "musig.nonce_gen", 1, "input_index" },
    { "musig.nonce_agg", 1, "input_index" },
    { "musig.nonce_agg", 2, "pubnonces" },
    { "musig.partial_sign", 1, "input_index" },
    { "musig.partial_sig_agg", 1, "input_index" },
    { "musig.partial_sig_agg", 2, "partial_sigs" },
    // cosign.* RPC conversion hints
    { "cosign.init", 3, "ttl" },
    { "cosign.send", 1, "payload" },
    { "cosign.recv", 1, "timeout_ms" },
    { "cosign.handshake_auto", 1, "is_initiator" },
    { "cosign.adaptor_roundtrip", 2, "is_initiator" },
    { "cosign.resume", 1, "from_seq" },
    // cosign bulletin board and governance RPC conversions
    { "cosign.init_bb", 0, "relays" },
    { "cosign.post_offer", 3, "amount" },
    { "cosign.post_offer", 4, "price" },
    { "cosign.post_offer", 5, "payment_methods" },
    { "cosign.post_offer", 6, "regions" },
    { "cosign.post_offer", 7, "requires_escrow" },
    { "cosign.post_offer", 8, "min_reputation_score" },
    { "cosign.post_contract_offer", 3, "apr" },
    { "cosign.post_contract_offer", 4, "ltv" },
    { "cosign.post_contract_offer", 5, "tenor_days" },
    { "cosign.post_contract_offer", 6, "proof_of_funds" },
    { "cosign.list_offers", 1, "min_amount" },
    { "cosign.list_offers", 2, "max_amount" },
    { "cosign.list_offers", 5, "min_reputation" },
    { "cosign.list_offers", 6, "force_refresh" },
    { "cosign.post_cross_chain_offer", 1, "proof_of_funds" },
    { "cosign.list_cross_chain_offers", 2, "force_refresh" },
    { "cosign.eth_lock_htlc", 4, "timelock" },
    { "cosign.eth_lock_htlc", 8, "gas_limit" },
    { "cosign.eth_lock_htlc", 9, "max_fee_gwei" },
    { "cosign.eth_lock_htlc", 10, "max_priority_fee_gwei" },
    { "cosign.eth_claim_htlc", 4, "gas_limit" },
    { "cosign.eth_claim_htlc", 5, "max_fee_gwei" },
    { "cosign.eth_claim_htlc", 6, "max_priority_fee_gwei" },
    { "cosign.eth_refund_htlc", 3, "gas_limit" },
    { "cosign.eth_refund_htlc", 4, "max_fee_gwei" },
    { "cosign.eth_refund_htlc", 5, "max_priority_fee_gwei" },
    { "cosign.eth_verify_attestation", 1, "attestation" },
    { "cosign.request_trade", 2, "proof_of_funds" },
    { "cosign.accept_request", 2, "ttl" },
    { "cosign.publish_governance", 0, "proposal" },
    { "cosign.publish_governance", 1, "rate_limit_secs" },
    { "cosign.list_governance", 1, "include_expired" },
    { "cosign.publish_ballot", 0, "ballot" },
    { "cosign.request_private_proposal", 4, "ownership_proof" },
    { "cosign.send_governance_ballot_dm", 4, "ballot_units" },
    { "cosign.process_governance_dms", 0, "since" },
    { "cosign.process_governance_dms", 1, "auto_approve" },
    { "cosign.send_proposal_response_manual", 2, "approve" },
    { "cosign.verify_discussion_proof", 4, "claimed_units" },
    { "cosign.discussion_post", 3, "expiry_blocks" },
    { "cosign.discussion_post", 4, "min_stake" },
    { "cosign.discussion_list", 2, "since" },
    { "cosign.discussion_list", 3, "limit" },
    { "cosign.discussion_list", 4, "force_refresh" },
    // Pricing RPC conversions
    { "pricing.market.calibrate", 1, "max_age_hours" },
    { "pricing.market.calibrate", 2, "decay_tau" },
    { "pricing.market.calibrate", 3, "min_volume" },
    { "pricing.market.push_vol_surface", 1, "strikes_pct" },
    { "pricing.market.push_vol_surface", 2, "maturities_days" },
    { "pricing.market.push_vol_surface", 3, "implied_vols" },
    { "pricing.market.push_fx", 2, "spot_rate" },
    { "pricing.market.push_fx", 3, "bid_ask_bps" },
    { "pricing.market.push_fx", 5, "base_is_native" },
    { "pricing.market.push_fx", 6, "quote_is_native" },
    { "pricing.market.push_curve", 1, "is_native" },
    { "pricing.market.push_curve", 2, "tenors_days" },
    { "pricing.market.push_curve", 3, "zero_rates" },
    { "pricing.market.push_correlation", 0, "asset_ids" },
    { "pricing.market.push_correlation", 1, "correlation_matrix" },
    { "pricing.market.push_difficulty_curve", 0, "horizons_blocks" },
    { "pricing.market.push_difficulty_curve", 1, "forward_nbits" },
    { "pricing.market.push_difficulty_surface", 0, "horizons_blocks" },
    { "pricing.market.push_difficulty_surface", 1, "sigmas" },
    { "pricing.market.model_difficulty_curve", 0, "drift_per_year" },
    { "pricing.market.model_difficulty_curve", 1, "horizons_blocks" },
    { "pricing.market.model_difficulty_curve", 2, "lookback_periods" },
    { "pricing.market.calibrate_difficulty_vol", 0, "lookback_periods" },
    { "pricing.market.calibrate_difficulty_vol", 1, "stride_blocks" },
    { "pricing.market.calibrate_difficulty_vol", 2, "horizons_blocks" },
    { "pricing.forward.quote", 2, "inline_terms" },
    { "pricing.forward.quote", 4, "report_is_native" },
    { "pricing.forward.quote", 5, "compute_greeks" },
    { "pricing.repo.quote", 2, "inline_terms" },
    { "pricing.repo.quote", 4, "report_is_native" },
    { "pricing.repo.quote", 5, "compute_greeks" },
    { "pricing.repo.quote", 7, "include_inception_cashflows" },
    { "pricing.diagnostics.scan", 2, "limit" },
    { "pricing.portfolio.summary", 1, "compute_greeks" },
    { "pricing.portfolio.risk", 0, "include_balances" },
    { "pricing.portfolio.risk", 1, "contract_ids" },
    { "pricing.portfolio.risk", 4, "report_is_native" },
    // Difficulty-derivative contract RPC conversions
    { "difficulty.propose", 0, "terms" },
    { "difficulty.propose_option", 0, "terms" },
    { "optionseries.derive", 0, "terms" },
    { "optionseries.derive", 1, "lots" },
    { "optionseries.verify", 1, "terms_source" },
    { "optionseries.verify", 2, "options" },
    { "optionseries.build_register", 0, "terms" },
    { "optionseries.build_register", 3, "options" },
    { "scalar.build_register", 0, "terms" },
    { "scalar.build_register", 4, "options" },
    { "scalar.build_issue", 0, "terms" },
    { "scalar.build_issue", 1, "options" },
    { "scalar.record_issue", 0, "terms" },
    { "scalar.build_redeem", 0, "terms" },
    { "scalar.build_redeem", 1, "redeem_long" },
    { "scalar.build_redeem", 2, "pots" },
    { "scalar.build_redeem", 3, "options" },
    { "scalar.build_unwind", 0, "terms" },
    { "scalar.build_unwind", 1, "lot_index" },
    { "scalar.build_unwind", 3, "options" },
    { "scalar.build_settlement", 0, "terms" },
    { "scalar.build_settlement", 1, "lot_index" },
    { "scalar.build_settlement", 3, "options" },
    { "scalarcfd.propose", 0, "terms" },
    { "scalarcfd.accept", 0, "offer" },
    { "scalarcfd.accept", 3, "options" },
    { "scalarcfd.import_acceptance", 0, "offer" },
    { "scalarcfd.import_acceptance", 1, "acceptance" },
    { "scalarcfd.build_open", 2, "options" },
    { "scalarcfd.build_settlement", 2, "options" },
    { "scalarcfd.build_coop_close", 2, "outputs" },
    { "scalarcfd.price", 1, "options" },
    { "optionseries.build_issue", 0, "terms" },
    { "optionseries.build_issue", 1, "options" },
    { "optionseries.record_issue", 0, "terms" },
    { "optionseries.build_settlement", 0, "terms" },
    { "optionseries.build_settlement", 1, "lot_index" },
    { "optionseries.build_settlement", 2, "options" },
    { "optionseries.build_redeem", 0, "terms" },
    { "optionseries.build_redeem", 1, "pots" },
    { "optionseries.build_redeem", 2, "options" },
    { "optionseries.build_buyback", 0, "terms" },
    { "optionseries.build_buyback", 1, "lot_index" },
    { "optionseries.build_buyback", 2, "options" },
    { "difficulty.accept", 0, "offer" },
    { "difficulty.accept", 3, "options" },
    { "difficulty.accept_option", 0, "offer" },
    { "difficulty.accept_option", 2, "options" },
    { "difficulty.import_acceptance", 0, "offer" },
    { "difficulty.import_acceptance", 1, "acceptance" },
    { "difficulty.build_open", 2, "options" },
    { "difficulty.build_open_option", 2, "options" },
    { "difficulty.build_settlement", 2, "options" },
    { "difficulty.build_coop_close", 2, "outputs" },
    { "pricing.difficulty.quote", 2, "inline_terms" },
    { "pricing.difficulty.quote", 3, "forecast_nbits" },
    { "pricing.difficulty.quote", 4, "compute_greeks" },
    // ICU acceptance RPC conversions
    { "icu.acceptance", 2, "options" },
    { "icu.acceptance.record.create", 2, "options" },
    { "icu.acceptance.record.verify", 1, "vout" },
    { "icu.acceptance.record.verify", 2, "options" },
    { "icu.acceptance.record.list", 1, "options" },
    { "icu.acceptance.prepare", 3, "holder_vout" },
    { "icu.acceptance.prepare", 4, "options" },
    { "icu.acceptance.verify", 3, "holder_vout" },
    { "icu.acceptance.verify", 6, "options" },
    { "icu.acceptance.record.prepare", 3, "holder_vout" },
    { "icu.acceptance.record.prepare", 4, "options" },
    { "icu.acceptance.record.assemble", 4, "holder_vout" },
    { "icu.acceptance.record.assemble", 6, "accepted_units" },
    { "icu.acceptance.record.assemble", 7, "sig_scheme" },
    { "icu.acceptance.record.assemble", 8, "body_refs" },
    { "icu.acceptance.record.assemble", 9, "client_signature" },
    // Forward contract RPC conversions
    { "forward.propose", 0, "terms" },
    { "forward.propose", 1, "options" },
    { "forward.import_offer", 0, "offer" },
    { "forward.accept", 0, "offer" },
    { "forward.accept", 1, "options" },
    { "forward.import_acceptance", 0, "acceptance" },
    { "forward.build_open", 1, "options" },
    { "forward.build_coop_close", 1, "settlement" },
    { "forward.build_coop_close", 2, "options" },
    { "forward.build_im_timeout", 2, "options" },
    { "forward.build_escrow_claim", 1, "escrow_outpoint" },
    { "forward.build_escrow_claim", 2, "options" },
    { "forward.build_escrow_refund", 1, "escrow_outpoint" },
    { "forward.build_escrow_refund", 2, "options" },
    { "forward.build_self_delivery", 1, "options" },
    { "forward.sign_over_channel", 2, "is_initiator" },
    { "forward.close_over_channel", 2, "settlement" },
    { "forward.close_over_channel", 3, "is_initiator" },
    { "forward.share_offer", 3, "ttl" },
    { "forward.collect_acceptance", 2, "timeout_ms" },
    // Repo contract additional conversions
    { "repo.share_offer", 3, "ttl" },
    { "repo.collect_acceptance", 2, "timeout_ms" },
    { "repo.sign_over_channel", 2, "is_initiator" },
    // Spot contract additional conversions
    { "spot.share_offer", 3, "ttl" },
    { "spot.collect_acceptance", 2, "timeout_ms" },
    { "spot.sign_over_channel", 2, "is_initiator" },
    // Asset rotation RPC conversions
    { "prepare_rotation", 1, "options" },
    { "finalize_rotation", 1, "options" },
    { "merge_rotation", 1, "ballot_psbts" },
    { "ballot", 1, "asset_utxos" },
    { "rotateasset", 1, "icu_vout" },
    { "rotateasset", 4, "options" },
    { "rotateicu", 1, "icu_vout" },
    { "rotateicu", 3, "unlock_fee_bump" },
    { "rotateicu", 5, "options" },
    { "rotateicu_raw", 1, "icu_vout" },
    { "rotateicu_raw", 3, "new_icu_amount" },
    { "rotateicu_raw", 5, "policy_bits" },
    { "rotateicu_raw", 6, "allowed_spk_families" },
    { "rotateicu_raw", 7, "unlock_fees_sats" },
    { "rotateicu_raw", 8, "options" },
    { "rotatezk", 1, "icu_vout" },
    { "rotatezk", 4, "options" },
    // ZK and asset tag conversions
    { "rawtxattachzkchunk", 1, "vout" },
    { "rawtxattachzkchunk", 4, "chunk_index" },
    { "rawtxattachzkchunk", 5, "chunk_count" },
    { "rawtxattachassettag", 5, "keywrap" },
    { "rawtxattachissuerreg", 8, "options" },
    { "generatezkproof", 3, "options" },
    // Adaptor signature conversions
    { "adaptor.prepare", 1, "musig2_config" },
    { "adaptor.prepare", 2, "allow_nontaproot_signeable_values" },
    // ML-DSA (post-quantum) RPC conversions
    { "generatemldsaaddress", 0, "level" },
    { "signmldsatransaction", 1, "input_index" },
    { "signmldsatransaction", 4, "level" },
    { "signmldsatransaction", 6, "prevout_value" },
    { "signmldsatransaction", 10, "parity" },
    { "signmldsatransaction", 12, "prevout_values" },
    { "signmldsatransaction", 13, "prevout_scriptpubkeys" },
    // ICU payload RPC conversions
    { "geticupayload", 1, "options" },
    { "buildcanonicalicupayload", 1, "witness_bundle" },
    { "buildcanonicalicupayload", 2, "visibility" },
    { "buildcanonicalicupayload", 3, "icu_context" },
    { "buildcanonicalicupayload", 4, "icu_clauses" },
    // Compliance root RPC conversions
    { "generatecomplianceroot", 0, "identities" },
    { "generatecomplianceroot", 2, "existing_tree" },
    // HD witness RPC conversions
    { "generatehdwitnessdata", 1, "country" },
    { "generatehdwitnessdata", 2, "age" },
    { "generatehdwitnessdata", 3, "merkle_index" },
    { "generatehdwitnessdata", 4, "merkle_proof" },
    { "generatehdwitnessdata", 5, "derivation" },
    // Asset distribution RPC conversions
    { "distributeasset", 1, "distribution_amount" },
    { "distributeasset", 2, "options" },
    // Contract list RPC conversions
    { "contract.list", 0, "filter" },
    // ML-DSA wallet RPC conversions
    { "signmldsatransactionwithwallet", 1, "prevtxs" },
};

// clang-format on

/** Parse string to UniValue or throw runtime_error if string contains invalid JSON */
static UniValue Parse(std::string_view raw)
{
    UniValue parsed;
    if (!parsed.read(raw)) throw std::runtime_error(tfm::format("Error parsing JSON: %s", raw));
    return parsed;
}

class CRPCConvertTable
{
private:
    std::set<std::pair<std::string, int>> members;
    std::set<std::pair<std::string, std::string>> membersByName;

public:
    CRPCConvertTable();

    /** Return arg_value as UniValue, and first parse it if it is a non-string parameter */
    UniValue ArgToUniValue(std::string_view arg_value, const std::string& method, int param_idx)
    {
        return members.count({method, param_idx}) > 0 ? Parse(arg_value) : arg_value;
    }

    /** Return arg_value as UniValue, and first parse it if it is a non-string parameter */
    UniValue ArgToUniValue(std::string_view arg_value, const std::string& method, const std::string& param_name)
    {
        return membersByName.count({method, param_name}) > 0 ? Parse(arg_value) : arg_value;
    }
};

CRPCConvertTable::CRPCConvertTable()
{
    for (const auto& cp : vRPCConvertParams) {
        members.emplace(cp.methodName, cp.paramIdx);
        membersByName.emplace(cp.methodName, cp.paramName);
    }
}

static CRPCConvertTable rpcCvtTable;

UniValue RPCConvertValues(const std::string &strMethod, const std::vector<std::string> &strParams)
{
    UniValue params(UniValue::VARR);

    for (unsigned int idx = 0; idx < strParams.size(); idx++) {
        std::string_view value{strParams[idx]};
        params.push_back(rpcCvtTable.ArgToUniValue(value, strMethod, idx));
    }

    return params;
}

UniValue RPCConvertNamedValues(const std::string &strMethod, const std::vector<std::string> &strParams)
{
    UniValue params(UniValue::VOBJ);
    UniValue positional_args{UniValue::VARR};

    for (std::string_view s: strParams) {
        size_t pos = s.find('=');
        if (pos == std::string::npos) {
            positional_args.push_back(rpcCvtTable.ArgToUniValue(s, strMethod, positional_args.size()));
            continue;
        }

        std::string name{s.substr(0, pos)};
        std::string_view value{s.substr(pos+1)};

        // Intentionally overwrite earlier named values with later ones as a
        // convenience for scripts and command line users that want to merge
        // options.
        params.pushKV(name, rpcCvtTable.ArgToUniValue(value, strMethod, name));
    }

    if (!positional_args.empty()) {
        // Use pushKVEnd instead of pushKV to avoid overwriting an explicit
        // "args" value with an implicit one. Let the RPC server handle the
        // request as given.
        params.pushKVEnd("args", std::move(positional_args));
    }

    return params;
}
