// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PROOF_PROOF_H_
#define FLATBUFFERS_GENERATED_PROOF_PROOF_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace proof {

struct FloatArray;
struct FloatArrayBuilder;

struct UIntArray;
struct UIntArrayBuilder;

struct Proof;
struct ProofBuilder;

struct FloatArray FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FloatArrayBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUES = 4
  };
  const ::flatbuffers::Vector<float> *values() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_VALUES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.EndTable();
  }
};

struct FloatArrayBuilder {
  typedef FloatArray Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<float>> values) {
    fbb_.AddOffset(FloatArray::VT_VALUES, values);
  }
  explicit FloatArrayBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FloatArray> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FloatArray>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FloatArray> CreateFloatArray(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> values = 0) {
  FloatArrayBuilder builder_(_fbb);
  builder_.add_values(values);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<FloatArray> CreateFloatArrayDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<float>(*values) : 0;
  return proof::CreateFloatArray(
      _fbb,
      values__);
}

struct UIntArray FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UIntArrayBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUES = 4
  };
  const ::flatbuffers::Vector<uint32_t> *values() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_VALUES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           verifier.EndTable();
  }
};

struct UIntArrayBuilder {
  typedef UIntArray Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> values) {
    fbb_.AddOffset(UIntArray::VT_VALUES, values);
  }
  explicit UIntArrayBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UIntArray> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UIntArray>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UIntArray> CreateUIntArray(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> values = 0) {
  UIntArrayBuilder builder_(_fbb);
  builder_.add_values(values);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<UIntArray> CreateUIntArrayDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint32_t> *values = nullptr) {
  auto values__ = values ? _fbb.CreateVector<uint32_t>(*values) : 0;
  return proof::CreateUIntArray(
      _fbb,
      values__);
}

struct Proof FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ProofBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_TICK = 6,
    VT_TIMESTAMP = 8,
    VT_TARGET = 10,
    VT_VDF = 12,
    VT_HASH = 14,
    VT_BLOCK_HASH = 16,
    VT_HEADER_PREFIX = 18,
    VT_IS_SOLUTION = 20,
    VT_MODEL_IDENTIFIER = 22,
    VT_COMPUTE_PRECISION = 24,
    VT_IPFS_CID = 26,
    VT_EXTRA_FLAGS = 28,
    VT_TEMPERATURE = 30,
    VT_TOP_P = 32,
    VT_TOP_K = 34,
    VT_REPETITION_PENALTY = 36,
    VT_CHOSEN_TOKENS = 38,
    VT_CHOSEN_PROBS = 40,
    VT_SAMPLING_U = 42,
    VT_SOFTMAX_NORMALIZERS = 44,
    VT_PROMPT_TOKENS = 46,
    VT_PAD_MASK = 48,
    VT_TOPK_LOGITS = 50,
    VT_TOPK_INDICES = 52,
    VT_LOGSUMEXP_STATS = 54
  };
  uint8_t version() const {
    return GetField<uint8_t>(VT_VERSION, 0);
  }
  uint64_t tick() const {
    return GetField<uint64_t>(VT_TICK, 0);
  }
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *target() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_TARGET);
  }
  const ::flatbuffers::Vector<uint8_t> *vdf() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_VDF);
  }
  const ::flatbuffers::Vector<uint8_t> *hash() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_HASH);
  }
  const ::flatbuffers::Vector<uint8_t> *block_hash() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_BLOCK_HASH);
  }
  const ::flatbuffers::Vector<uint8_t> *header_prefix() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_HEADER_PREFIX);
  }
  bool is_solution() const {
    return GetField<uint8_t>(VT_IS_SOLUTION, 0) != 0;
  }
  const ::flatbuffers::String *model_identifier() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MODEL_IDENTIFIER);
  }
  const ::flatbuffers::String *compute_precision() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COMPUTE_PRECISION);
  }
  const ::flatbuffers::String *ipfs_cid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_IPFS_CID);
  }
  const ::flatbuffers::String *extra_flags() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EXTRA_FLAGS);
  }
  float temperature() const {
    return GetField<float>(VT_TEMPERATURE, 0.0f);
  }
  float top_p() const {
    return GetField<float>(VT_TOP_P, 0.0f);
  }
  uint32_t top_k() const {
    return GetField<uint32_t>(VT_TOP_K, 0);
  }
  float repetition_penalty() const {
    return GetField<float>(VT_REPETITION_PENALTY, 0.0f);
  }
  const ::flatbuffers::Vector<uint32_t> *chosen_tokens() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_CHOSEN_TOKENS);
  }
  const ::flatbuffers::Vector<float> *chosen_probs() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_CHOSEN_PROBS);
  }
  const ::flatbuffers::Vector<float> *sampling_u() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_SAMPLING_U);
  }
  const ::flatbuffers::Vector<float> *softmax_normalizers() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_SOFTMAX_NORMALIZERS);
  }
  const ::flatbuffers::Vector<uint32_t> *prompt_tokens() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_PROMPT_TOKENS);
  }
  const ::flatbuffers::Vector<uint8_t> *pad_mask() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_PAD_MASK);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<proof::FloatArray>> *topk_logits() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<proof::FloatArray>> *>(VT_TOPK_LOGITS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<proof::UIntArray>> *topk_indices() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<proof::UIntArray>> *>(VT_TOPK_INDICES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<proof::FloatArray>> *logsumexp_stats() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<proof::FloatArray>> *>(VT_LOGSUMEXP_STATS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_VERSION, 1) &&
           VerifyField<uint64_t>(verifier, VT_TICK, 8) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP, 8) &&
           VerifyOffset(verifier, VT_TARGET) &&
           verifier.VerifyVector(target()) &&
           VerifyOffset(verifier, VT_VDF) &&
           verifier.VerifyVector(vdf()) &&
           VerifyOffset(verifier, VT_HASH) &&
           verifier.VerifyVector(hash()) &&
           VerifyOffset(verifier, VT_BLOCK_HASH) &&
           verifier.VerifyVector(block_hash()) &&
           VerifyOffset(verifier, VT_HEADER_PREFIX) &&
           verifier.VerifyVector(header_prefix()) &&
           VerifyField<uint8_t>(verifier, VT_IS_SOLUTION, 1) &&
           VerifyOffset(verifier, VT_MODEL_IDENTIFIER) &&
           verifier.VerifyString(model_identifier()) &&
           VerifyOffset(verifier, VT_COMPUTE_PRECISION) &&
           verifier.VerifyString(compute_precision()) &&
           VerifyOffset(verifier, VT_IPFS_CID) &&
           verifier.VerifyString(ipfs_cid()) &&
           VerifyOffset(verifier, VT_EXTRA_FLAGS) &&
           verifier.VerifyString(extra_flags()) &&
           VerifyField<float>(verifier, VT_TEMPERATURE, 4) &&
           VerifyField<float>(verifier, VT_TOP_P, 4) &&
           VerifyField<uint32_t>(verifier, VT_TOP_K, 4) &&
           VerifyField<float>(verifier, VT_REPETITION_PENALTY, 4) &&
           VerifyOffset(verifier, VT_CHOSEN_TOKENS) &&
           verifier.VerifyVector(chosen_tokens()) &&
           VerifyOffset(verifier, VT_CHOSEN_PROBS) &&
           verifier.VerifyVector(chosen_probs()) &&
           VerifyOffset(verifier, VT_SAMPLING_U) &&
           verifier.VerifyVector(sampling_u()) &&
           VerifyOffset(verifier, VT_SOFTMAX_NORMALIZERS) &&
           verifier.VerifyVector(softmax_normalizers()) &&
           VerifyOffset(verifier, VT_PROMPT_TOKENS) &&
           verifier.VerifyVector(prompt_tokens()) &&
           VerifyOffset(verifier, VT_PAD_MASK) &&
           verifier.VerifyVector(pad_mask()) &&
           VerifyOffset(verifier, VT_TOPK_LOGITS) &&
           verifier.VerifyVector(topk_logits()) &&
           verifier.VerifyVectorOfTables(topk_logits()) &&
           VerifyOffset(verifier, VT_TOPK_INDICES) &&
           verifier.VerifyVector(topk_indices()) &&
           verifier.VerifyVectorOfTables(topk_indices()) &&
           VerifyOffset(verifier, VT_LOGSUMEXP_STATS) &&
           verifier.VerifyVector(logsumexp_stats()) &&
           verifier.VerifyVectorOfTables(logsumexp_stats()) &&
           verifier.EndTable();
  }
};

struct ProofBuilder {
  typedef Proof Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_version(uint8_t version) {
    fbb_.AddElement<uint8_t>(Proof::VT_VERSION, version, 0);
  }
  void add_tick(uint64_t tick) {
    fbb_.AddElement<uint64_t>(Proof::VT_TICK, tick, 0);
  }
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(Proof::VT_TIMESTAMP, timestamp, 0);
  }
  void add_target(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> target) {
    fbb_.AddOffset(Proof::VT_TARGET, target);
  }
  void add_vdf(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> vdf) {
    fbb_.AddOffset(Proof::VT_VDF, vdf);
  }
  void add_hash(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> hash) {
    fbb_.AddOffset(Proof::VT_HASH, hash);
  }
  void add_block_hash(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> block_hash) {
    fbb_.AddOffset(Proof::VT_BLOCK_HASH, block_hash);
  }
  void add_header_prefix(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> header_prefix) {
    fbb_.AddOffset(Proof::VT_HEADER_PREFIX, header_prefix);
  }
  void add_is_solution(bool is_solution) {
    fbb_.AddElement<uint8_t>(Proof::VT_IS_SOLUTION, static_cast<uint8_t>(is_solution), 0);
  }
  void add_model_identifier(::flatbuffers::Offset<::flatbuffers::String> model_identifier) {
    fbb_.AddOffset(Proof::VT_MODEL_IDENTIFIER, model_identifier);
  }
  void add_compute_precision(::flatbuffers::Offset<::flatbuffers::String> compute_precision) {
    fbb_.AddOffset(Proof::VT_COMPUTE_PRECISION, compute_precision);
  }
  void add_ipfs_cid(::flatbuffers::Offset<::flatbuffers::String> ipfs_cid) {
    fbb_.AddOffset(Proof::VT_IPFS_CID, ipfs_cid);
  }
  void add_extra_flags(::flatbuffers::Offset<::flatbuffers::String> extra_flags) {
    fbb_.AddOffset(Proof::VT_EXTRA_FLAGS, extra_flags);
  }
  void add_temperature(float temperature) {
    fbb_.AddElement<float>(Proof::VT_TEMPERATURE, temperature, 0.0f);
  }
  void add_top_p(float top_p) {
    fbb_.AddElement<float>(Proof::VT_TOP_P, top_p, 0.0f);
  }
  void add_top_k(uint32_t top_k) {
    fbb_.AddElement<uint32_t>(Proof::VT_TOP_K, top_k, 0);
  }
  void add_repetition_penalty(float repetition_penalty) {
    fbb_.AddElement<float>(Proof::VT_REPETITION_PENALTY, repetition_penalty, 0.0f);
  }
  void add_chosen_tokens(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> chosen_tokens) {
    fbb_.AddOffset(Proof::VT_CHOSEN_TOKENS, chosen_tokens);
  }
  void add_chosen_probs(::flatbuffers::Offset<::flatbuffers::Vector<float>> chosen_probs) {
    fbb_.AddOffset(Proof::VT_CHOSEN_PROBS, chosen_probs);
  }
  void add_sampling_u(::flatbuffers::Offset<::flatbuffers::Vector<float>> sampling_u) {
    fbb_.AddOffset(Proof::VT_SAMPLING_U, sampling_u);
  }
  void add_softmax_normalizers(::flatbuffers::Offset<::flatbuffers::Vector<float>> softmax_normalizers) {
    fbb_.AddOffset(Proof::VT_SOFTMAX_NORMALIZERS, softmax_normalizers);
  }
  void add_prompt_tokens(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> prompt_tokens) {
    fbb_.AddOffset(Proof::VT_PROMPT_TOKENS, prompt_tokens);
  }
  void add_pad_mask(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> pad_mask) {
    fbb_.AddOffset(Proof::VT_PAD_MASK, pad_mask);
  }
  void add_topk_logits(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<proof::FloatArray>>> topk_logits) {
    fbb_.AddOffset(Proof::VT_TOPK_LOGITS, topk_logits);
  }
  void add_topk_indices(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<proof::UIntArray>>> topk_indices) {
    fbb_.AddOffset(Proof::VT_TOPK_INDICES, topk_indices);
  }
  void add_logsumexp_stats(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<proof::FloatArray>>> logsumexp_stats) {
    fbb_.AddOffset(Proof::VT_LOGSUMEXP_STATS, logsumexp_stats);
  }
  explicit ProofBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Proof> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Proof>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Proof> CreateProof(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t version = 0,
    uint64_t tick = 0,
    uint64_t timestamp = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> target = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> vdf = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> hash = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> block_hash = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> header_prefix = 0,
    bool is_solution = false,
    ::flatbuffers::Offset<::flatbuffers::String> model_identifier = 0,
    ::flatbuffers::Offset<::flatbuffers::String> compute_precision = 0,
    ::flatbuffers::Offset<::flatbuffers::String> ipfs_cid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> extra_flags = 0,
    float temperature = 0.0f,
    float top_p = 0.0f,
    uint32_t top_k = 0,
    float repetition_penalty = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> chosen_tokens = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> chosen_probs = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> sampling_u = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> softmax_normalizers = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> prompt_tokens = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> pad_mask = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<proof::FloatArray>>> topk_logits = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<proof::UIntArray>>> topk_indices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<proof::FloatArray>>> logsumexp_stats = 0) {
  ProofBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_tick(tick);
  builder_.add_logsumexp_stats(logsumexp_stats);
  builder_.add_topk_indices(topk_indices);
  builder_.add_topk_logits(topk_logits);
  builder_.add_pad_mask(pad_mask);
  builder_.add_prompt_tokens(prompt_tokens);
  builder_.add_softmax_normalizers(softmax_normalizers);
  builder_.add_sampling_u(sampling_u);
  builder_.add_chosen_probs(chosen_probs);
  builder_.add_chosen_tokens(chosen_tokens);
  builder_.add_repetition_penalty(repetition_penalty);
  builder_.add_top_k(top_k);
  builder_.add_top_p(top_p);
  builder_.add_temperature(temperature);
  builder_.add_extra_flags(extra_flags);
  builder_.add_ipfs_cid(ipfs_cid);
  builder_.add_compute_precision(compute_precision);
  builder_.add_model_identifier(model_identifier);
  builder_.add_header_prefix(header_prefix);
  builder_.add_block_hash(block_hash);
  builder_.add_hash(hash);
  builder_.add_vdf(vdf);
  builder_.add_target(target);
  builder_.add_is_solution(is_solution);
  builder_.add_version(version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Proof> CreateProofDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t version = 0,
    uint64_t tick = 0,
    uint64_t timestamp = 0,
    const std::vector<uint8_t> *target = nullptr,
    const std::vector<uint8_t> *vdf = nullptr,
    const std::vector<uint8_t> *hash = nullptr,
    const std::vector<uint8_t> *block_hash = nullptr,
    const std::vector<uint8_t> *header_prefix = nullptr,
    bool is_solution = false,
    const char *model_identifier = nullptr,
    const char *compute_precision = nullptr,
    const char *ipfs_cid = nullptr,
    const char *extra_flags = nullptr,
    float temperature = 0.0f,
    float top_p = 0.0f,
    uint32_t top_k = 0,
    float repetition_penalty = 0.0f,
    const std::vector<uint32_t> *chosen_tokens = nullptr,
    const std::vector<float> *chosen_probs = nullptr,
    const std::vector<float> *sampling_u = nullptr,
    const std::vector<float> *softmax_normalizers = nullptr,
    const std::vector<uint32_t> *prompt_tokens = nullptr,
    const std::vector<uint8_t> *pad_mask = nullptr,
    const std::vector<::flatbuffers::Offset<proof::FloatArray>> *topk_logits = nullptr,
    const std::vector<::flatbuffers::Offset<proof::UIntArray>> *topk_indices = nullptr,
    const std::vector<::flatbuffers::Offset<proof::FloatArray>> *logsumexp_stats = nullptr) {
  auto target__ = target ? _fbb.CreateVector<uint8_t>(*target) : 0;
  auto vdf__ = vdf ? _fbb.CreateVector<uint8_t>(*vdf) : 0;
  auto hash__ = hash ? _fbb.CreateVector<uint8_t>(*hash) : 0;
  auto block_hash__ = block_hash ? _fbb.CreateVector<uint8_t>(*block_hash) : 0;
  auto header_prefix__ = header_prefix ? _fbb.CreateVector<uint8_t>(*header_prefix) : 0;
  auto model_identifier__ = model_identifier ? _fbb.CreateString(model_identifier) : 0;
  auto compute_precision__ = compute_precision ? _fbb.CreateString(compute_precision) : 0;
  auto ipfs_cid__ = ipfs_cid ? _fbb.CreateString(ipfs_cid) : 0;
  auto extra_flags__ = extra_flags ? _fbb.CreateString(extra_flags) : 0;
  auto chosen_tokens__ = chosen_tokens ? _fbb.CreateVector<uint32_t>(*chosen_tokens) : 0;
  auto chosen_probs__ = chosen_probs ? _fbb.CreateVector<float>(*chosen_probs) : 0;
  auto sampling_u__ = sampling_u ? _fbb.CreateVector<float>(*sampling_u) : 0;
  auto softmax_normalizers__ = softmax_normalizers ? _fbb.CreateVector<float>(*softmax_normalizers) : 0;
  auto prompt_tokens__ = prompt_tokens ? _fbb.CreateVector<uint32_t>(*prompt_tokens) : 0;
  auto pad_mask__ = pad_mask ? _fbb.CreateVector<uint8_t>(*pad_mask) : 0;
  auto topk_logits__ = topk_logits ? _fbb.CreateVector<::flatbuffers::Offset<proof::FloatArray>>(*topk_logits) : 0;
  auto topk_indices__ = topk_indices ? _fbb.CreateVector<::flatbuffers::Offset<proof::UIntArray>>(*topk_indices) : 0;
  auto logsumexp_stats__ = logsumexp_stats ? _fbb.CreateVector<::flatbuffers::Offset<proof::FloatArray>>(*logsumexp_stats) : 0;
  return proof::CreateProof(
      _fbb,
      version,
      tick,
      timestamp,
      target__,
      vdf__,
      hash__,
      block_hash__,
      header_prefix__,
      is_solution,
      model_identifier__,
      compute_precision__,
      ipfs_cid__,
      extra_flags__,
      temperature,
      top_p,
      top_k,
      repetition_penalty,
      chosen_tokens__,
      chosen_probs__,
      sampling_u__,
      softmax_normalizers__,
      prompt_tokens__,
      pad_mask__,
      topk_logits__,
      topk_indices__,
      logsumexp_stats__);
}

inline const proof::Proof *GetProof(const void *buf) {
  return ::flatbuffers::GetRoot<proof::Proof>(buf);
}

inline const proof::Proof *GetSizePrefixedProof(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<proof::Proof>(buf);
}

inline const char *ProofIdentifier() {
  return "PROF";
}

inline bool ProofBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, ProofIdentifier());
}

inline bool SizePrefixedProofBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, ProofIdentifier(), true);
}

inline bool VerifyProofBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<proof::Proof>(ProofIdentifier());
}

inline bool VerifySizePrefixedProofBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<proof::Proof>(ProofIdentifier());
}

inline void FinishProofBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<proof::Proof> root) {
  fbb.Finish(root, ProofIdentifier());
}

inline void FinishSizePrefixedProofBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<proof::Proof> root) {
  fbb.FinishSizePrefixed(root, ProofIdentifier());
}

}  // namespace proof

#endif  // FLATBUFFERS_GENERATED_PROOF_PROOF_H_
