// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_VALIDATION_PROOF_H_
#define FLATBUFFERS_GENERATED_VALIDATION_PROOF_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "proof_generated.h"

namespace proof {

struct BlockValidation;
struct BlockValidationBuilder;

struct ModelValidation;
struct ModelValidationBuilder;

struct ValidationRequest;
struct ValidationRequestBuilder;

struct ValidationResponse;
struct ValidationResponseBuilder;

enum ValidationType : uint8_t {
  ValidationType_Quick = 0,
  ValidationType_Quick_Smell = 1,
  ValidationType_Full = 2,
  ValidationType_Model = 3,
  ValidationType_Challenge = 4,
  ValidationType_Logits = 5,
  ValidationType_MIN = ValidationType_Quick,
  ValidationType_MAX = ValidationType_Logits
};

inline const ValidationType (&EnumValuesValidationType())[6] {
  static const ValidationType values[] = {
    ValidationType_Quick,
    ValidationType_Quick_Smell,
    ValidationType_Full,
    ValidationType_Model,
    ValidationType_Challenge,
    ValidationType_Logits
  };
  return values;
}

inline const char * const *EnumNamesValidationType() {
  static const char * const names[7] = {
    "Quick",
    "Quick_Smell",
    "Full",
    "Model",
    "Challenge",
    "Logits",
    nullptr
  };
  return names;
}

inline const char *EnumNameValidationType(ValidationType e) {
  if (::flatbuffers::IsOutRange(e, ValidationType_Quick, ValidationType_Logits)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesValidationType()[index];
}

enum ResponseValue : uint8_t {
  ResponseValue_Quick_OK = 0,
  ResponseValue_Quick_Fail = 1,
  ResponseValue_Quick_OK_Smell_OK = 2,
  ResponseValue_Quick_OK_Smell_Fail = 3,
  ResponseValue_Quick_Fail_Smell_OK = 4,
  ResponseValue_Quick_Fail_Smell_Fail = 5,
  ResponseValue_Full_Green = 6,
  ResponseValue_Full_Amber = 7,
  ResponseValue_Full_Red = 8,
  ResponseValue_Model_OK = 9,
  ResponseValue_Model_Fail = 10,
  ResponseValue_Challenge_OK = 11,
  ResponseValue_Challenge_Fail = 12,
  ResponseValue_Model_Pending_Review = 13,
  ResponseValue_Logits_OK = 14,
  ResponseValue_Logits_Fail = 15,
  ResponseValue_MIN = ResponseValue_Quick_OK,
  ResponseValue_MAX = ResponseValue_Logits_Fail
};

inline const ResponseValue (&EnumValuesResponseValue())[16] {
  static const ResponseValue values[] = {
    ResponseValue_Quick_OK,
    ResponseValue_Quick_Fail,
    ResponseValue_Quick_OK_Smell_OK,
    ResponseValue_Quick_OK_Smell_Fail,
    ResponseValue_Quick_Fail_Smell_OK,
    ResponseValue_Quick_Fail_Smell_Fail,
    ResponseValue_Full_Green,
    ResponseValue_Full_Amber,
    ResponseValue_Full_Red,
    ResponseValue_Model_OK,
    ResponseValue_Model_Fail,
    ResponseValue_Challenge_OK,
    ResponseValue_Challenge_Fail,
    ResponseValue_Model_Pending_Review,
    ResponseValue_Logits_OK,
    ResponseValue_Logits_Fail
  };
  return values;
}

inline const char * const *EnumNamesResponseValue() {
  static const char * const names[17] = {
    "Quick_OK",
    "Quick_Fail",
    "Quick_OK_Smell_OK",
    "Quick_OK_Smell_Fail",
    "Quick_Fail_Smell_OK",
    "Quick_Fail_Smell_Fail",
    "Full_Green",
    "Full_Amber",
    "Full_Red",
    "Model_OK",
    "Model_Fail",
    "Challenge_OK",
    "Challenge_Fail",
    "Model_Pending_Review",
    "Logits_OK",
    "Logits_Fail",
    nullptr
  };
  return names;
}

inline const char *EnumNameResponseValue(ResponseValue e) {
  if (::flatbuffers::IsOutRange(e, ResponseValue_Quick_OK, ResponseValue_Logits_Fail)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesResponseValue()[index];
}

enum ValidationUnion : uint8_t {
  ValidationUnion_NONE = 0,
  ValidationUnion_BlockValidation = 1,
  ValidationUnion_ModelValidation = 2,
  ValidationUnion_MIN = ValidationUnion_NONE,
  ValidationUnion_MAX = ValidationUnion_ModelValidation
};

inline const ValidationUnion (&EnumValuesValidationUnion())[3] {
  static const ValidationUnion values[] = {
    ValidationUnion_NONE,
    ValidationUnion_BlockValidation,
    ValidationUnion_ModelValidation
  };
  return values;
}

inline const char * const *EnumNamesValidationUnion() {
  static const char * const names[4] = {
    "NONE",
    "BlockValidation",
    "ModelValidation",
    nullptr
  };
  return names;
}

inline const char *EnumNameValidationUnion(ValidationUnion e) {
  if (::flatbuffers::IsOutRange(e, ValidationUnion_NONE, ValidationUnion_ModelValidation)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesValidationUnion()[index];
}

template<typename T> struct ValidationUnionTraits {
  static const ValidationUnion enum_value = ValidationUnion_NONE;
};

template<> struct ValidationUnionTraits<proof::BlockValidation> {
  static const ValidationUnion enum_value = ValidationUnion_BlockValidation;
};

template<> struct ValidationUnionTraits<proof::ModelValidation> {
  static const ValidationUnion enum_value = ValidationUnion_ModelValidation;
};

bool VerifyValidationUnion(::flatbuffers::Verifier &verifier, const void *obj, ValidationUnion type);
bool VerifyValidationUnionVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct BlockValidation FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BlockValidationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_HASH = 6,
    VT_PREV_BLOCK_HASH = 8,
    VT_MERKLE_ROOT = 10,
    VT_TIMESTAMP = 12,
    VT_BITS = 14,
    VT_NONCE = 16,
    VT_POW_BLOB_HASH = 18,
    VT_ADJUSTED_BITS = 20,
    VT_POW_BLOB = 22,
    VT_DIFFICULTY = 24
  };
  uint32_t version() const {
    return GetField<uint32_t>(VT_VERSION, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *hash() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_HASH);
  }
  const ::flatbuffers::Vector<uint8_t> *prev_block_hash() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_PREV_BLOCK_HASH);
  }
  const ::flatbuffers::Vector<uint8_t> *merkle_root() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_MERKLE_ROOT);
  }
  uint32_t timestamp() const {
    return GetField<uint32_t>(VT_TIMESTAMP, 0);
  }
  uint32_t bits() const {
    return GetField<uint32_t>(VT_BITS, 0);
  }
  uint32_t nonce() const {
    return GetField<uint32_t>(VT_NONCE, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *pow_blob_hash() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_POW_BLOB_HASH);
  }
  uint32_t adjusted_bits() const {
    return GetField<uint32_t>(VT_ADJUSTED_BITS, 0);
  }
  const proof::Proof *pow_blob() const {
    return GetPointer<const proof::Proof *>(VT_POW_BLOB);
  }
  int64_t difficulty() const {
    return GetField<int64_t>(VT_DIFFICULTY, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyOffset(verifier, VT_HASH) &&
           verifier.VerifyVector(hash()) &&
           VerifyOffset(verifier, VT_PREV_BLOCK_HASH) &&
           verifier.VerifyVector(prev_block_hash()) &&
           VerifyOffset(verifier, VT_MERKLE_ROOT) &&
           verifier.VerifyVector(merkle_root()) &&
           VerifyField<uint32_t>(verifier, VT_TIMESTAMP, 4) &&
           VerifyField<uint32_t>(verifier, VT_BITS, 4) &&
           VerifyField<uint32_t>(verifier, VT_NONCE, 4) &&
           VerifyOffset(verifier, VT_POW_BLOB_HASH) &&
           verifier.VerifyVector(pow_blob_hash()) &&
           VerifyField<uint32_t>(verifier, VT_ADJUSTED_BITS, 4) &&
           VerifyOffset(verifier, VT_POW_BLOB) &&
           verifier.VerifyTable(pow_blob()) &&
           VerifyField<int64_t>(verifier, VT_DIFFICULTY, 8) &&
           verifier.EndTable();
  }
};

struct BlockValidationBuilder {
  typedef BlockValidation Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_version(uint32_t version) {
    fbb_.AddElement<uint32_t>(BlockValidation::VT_VERSION, version, 0);
  }
  void add_hash(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> hash) {
    fbb_.AddOffset(BlockValidation::VT_HASH, hash);
  }
  void add_prev_block_hash(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> prev_block_hash) {
    fbb_.AddOffset(BlockValidation::VT_PREV_BLOCK_HASH, prev_block_hash);
  }
  void add_merkle_root(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> merkle_root) {
    fbb_.AddOffset(BlockValidation::VT_MERKLE_ROOT, merkle_root);
  }
  void add_timestamp(uint32_t timestamp) {
    fbb_.AddElement<uint32_t>(BlockValidation::VT_TIMESTAMP, timestamp, 0);
  }
  void add_bits(uint32_t bits) {
    fbb_.AddElement<uint32_t>(BlockValidation::VT_BITS, bits, 0);
  }
  void add_nonce(uint32_t nonce) {
    fbb_.AddElement<uint32_t>(BlockValidation::VT_NONCE, nonce, 0);
  }
  void add_pow_blob_hash(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> pow_blob_hash) {
    fbb_.AddOffset(BlockValidation::VT_POW_BLOB_HASH, pow_blob_hash);
  }
  void add_adjusted_bits(uint32_t adjusted_bits) {
    fbb_.AddElement<uint32_t>(BlockValidation::VT_ADJUSTED_BITS, adjusted_bits, 0);
  }
  void add_pow_blob(::flatbuffers::Offset<proof::Proof> pow_blob) {
    fbb_.AddOffset(BlockValidation::VT_POW_BLOB, pow_blob);
  }
  void add_difficulty(int64_t difficulty) {
    fbb_.AddElement<int64_t>(BlockValidation::VT_DIFFICULTY, difficulty, 0);
  }
  explicit BlockValidationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BlockValidation> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BlockValidation>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BlockValidation> CreateBlockValidation(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t version = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> hash = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> prev_block_hash = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> merkle_root = 0,
    uint32_t timestamp = 0,
    uint32_t bits = 0,
    uint32_t nonce = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> pow_blob_hash = 0,
    uint32_t adjusted_bits = 0,
    ::flatbuffers::Offset<proof::Proof> pow_blob = 0,
    int64_t difficulty = 0) {
  BlockValidationBuilder builder_(_fbb);
  builder_.add_difficulty(difficulty);
  builder_.add_pow_blob(pow_blob);
  builder_.add_adjusted_bits(adjusted_bits);
  builder_.add_pow_blob_hash(pow_blob_hash);
  builder_.add_nonce(nonce);
  builder_.add_bits(bits);
  builder_.add_timestamp(timestamp);
  builder_.add_merkle_root(merkle_root);
  builder_.add_prev_block_hash(prev_block_hash);
  builder_.add_hash(hash);
  builder_.add_version(version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BlockValidation> CreateBlockValidationDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t version = 0,
    const std::vector<uint8_t> *hash = nullptr,
    const std::vector<uint8_t> *prev_block_hash = nullptr,
    const std::vector<uint8_t> *merkle_root = nullptr,
    uint32_t timestamp = 0,
    uint32_t bits = 0,
    uint32_t nonce = 0,
    const std::vector<uint8_t> *pow_blob_hash = nullptr,
    uint32_t adjusted_bits = 0,
    ::flatbuffers::Offset<proof::Proof> pow_blob = 0,
    int64_t difficulty = 0) {
  auto hash__ = hash ? _fbb.CreateVector<uint8_t>(*hash) : 0;
  auto prev_block_hash__ = prev_block_hash ? _fbb.CreateVector<uint8_t>(*prev_block_hash) : 0;
  auto merkle_root__ = merkle_root ? _fbb.CreateVector<uint8_t>(*merkle_root) : 0;
  auto pow_blob_hash__ = pow_blob_hash ? _fbb.CreateVector<uint8_t>(*pow_blob_hash) : 0;
  return proof::CreateBlockValidation(
      _fbb,
      version,
      hash__,
      prev_block_hash__,
      merkle_root__,
      timestamp,
      bits,
      nonce,
      pow_blob_hash__,
      adjusted_bits,
      pow_blob,
      difficulty);
}

struct ModelValidation FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ModelValidationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MODEL_NAME = 4,
    VT_MODEL_COMMIT = 6,
    VT_DIFFICULTY = 8,
    VT_CID = 10,
    VT_EXTRA = 12,
    VT_TXID = 14,
    VT_BLOCK_HASH = 16,
    VT_BLOCK_HEIGHT = 18
  };
  const ::flatbuffers::String *model_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MODEL_NAME);
  }
  const ::flatbuffers::String *model_commit() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MODEL_COMMIT);
  }
  int64_t difficulty() const {
    return GetField<int64_t>(VT_DIFFICULTY, 0);
  }
  const ::flatbuffers::String *cid() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CID);
  }
  const ::flatbuffers::String *extra() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EXTRA);
  }
  const ::flatbuffers::Vector<uint8_t> *txid() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_TXID);
  }
  const ::flatbuffers::Vector<uint8_t> *block_hash() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_BLOCK_HASH);
  }
  int32_t block_height() const {
    return GetField<int32_t>(VT_BLOCK_HEIGHT, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MODEL_NAME) &&
           verifier.VerifyString(model_name()) &&
           VerifyOffset(verifier, VT_MODEL_COMMIT) &&
           verifier.VerifyString(model_commit()) &&
           VerifyField<int64_t>(verifier, VT_DIFFICULTY, 8) &&
           VerifyOffset(verifier, VT_CID) &&
           verifier.VerifyString(cid()) &&
           VerifyOffset(verifier, VT_EXTRA) &&
           verifier.VerifyString(extra()) &&
           VerifyOffset(verifier, VT_TXID) &&
           verifier.VerifyVector(txid()) &&
           VerifyOffset(verifier, VT_BLOCK_HASH) &&
           verifier.VerifyVector(block_hash()) &&
           VerifyField<int32_t>(verifier, VT_BLOCK_HEIGHT, 4) &&
           verifier.EndTable();
  }
};

struct ModelValidationBuilder {
  typedef ModelValidation Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_model_name(::flatbuffers::Offset<::flatbuffers::String> model_name) {
    fbb_.AddOffset(ModelValidation::VT_MODEL_NAME, model_name);
  }
  void add_model_commit(::flatbuffers::Offset<::flatbuffers::String> model_commit) {
    fbb_.AddOffset(ModelValidation::VT_MODEL_COMMIT, model_commit);
  }
  void add_difficulty(int64_t difficulty) {
    fbb_.AddElement<int64_t>(ModelValidation::VT_DIFFICULTY, difficulty, 0);
  }
  void add_cid(::flatbuffers::Offset<::flatbuffers::String> cid) {
    fbb_.AddOffset(ModelValidation::VT_CID, cid);
  }
  void add_extra(::flatbuffers::Offset<::flatbuffers::String> extra) {
    fbb_.AddOffset(ModelValidation::VT_EXTRA, extra);
  }
  void add_txid(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> txid) {
    fbb_.AddOffset(ModelValidation::VT_TXID, txid);
  }
  void add_block_hash(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> block_hash) {
    fbb_.AddOffset(ModelValidation::VT_BLOCK_HASH, block_hash);
  }
  void add_block_height(int32_t block_height) {
    fbb_.AddElement<int32_t>(ModelValidation::VT_BLOCK_HEIGHT, block_height, 0);
  }
  explicit ModelValidationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ModelValidation> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ModelValidation>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ModelValidation> CreateModelValidation(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> model_name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> model_commit = 0,
    int64_t difficulty = 0,
    ::flatbuffers::Offset<::flatbuffers::String> cid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> extra = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> txid = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> block_hash = 0,
    int32_t block_height = 0) {
  ModelValidationBuilder builder_(_fbb);
  builder_.add_difficulty(difficulty);
  builder_.add_block_height(block_height);
  builder_.add_block_hash(block_hash);
  builder_.add_txid(txid);
  builder_.add_extra(extra);
  builder_.add_cid(cid);
  builder_.add_model_commit(model_commit);
  builder_.add_model_name(model_name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ModelValidation> CreateModelValidationDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *model_name = nullptr,
    const char *model_commit = nullptr,
    int64_t difficulty = 0,
    const char *cid = nullptr,
    const char *extra = nullptr,
    const std::vector<uint8_t> *txid = nullptr,
    const std::vector<uint8_t> *block_hash = nullptr,
    int32_t block_height = 0) {
  auto model_name__ = model_name ? _fbb.CreateString(model_name) : 0;
  auto model_commit__ = model_commit ? _fbb.CreateString(model_commit) : 0;
  auto cid__ = cid ? _fbb.CreateString(cid) : 0;
  auto extra__ = extra ? _fbb.CreateString(extra) : 0;
  auto txid__ = txid ? _fbb.CreateVector<uint8_t>(*txid) : 0;
  auto block_hash__ = block_hash ? _fbb.CreateVector<uint8_t>(*block_hash) : 0;
  return proof::CreateModelValidation(
      _fbb,
      model_name__,
      model_commit__,
      difficulty,
      cid__,
      extra__,
      txid__,
      block_hash__,
      block_height);
}

struct ValidationRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ValidationRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HASH_ID = 4,
    VT_VALIDATION_TYPE = 6,
    VT_REQUEST_TYPE = 8,
    VT_REQUEST = 10
  };
  const ::flatbuffers::Vector<uint8_t> *hash_id() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_HASH_ID);
  }
  proof::ValidationType validation_type() const {
    return static_cast<proof::ValidationType>(GetField<uint8_t>(VT_VALIDATION_TYPE, 0));
  }
  proof::ValidationUnion request_type() const {
    return static_cast<proof::ValidationUnion>(GetField<uint8_t>(VT_REQUEST_TYPE, 0));
  }
  const void *request() const {
    return GetPointer<const void *>(VT_REQUEST);
  }
  template<typename T> const T *request_as() const;
  const proof::BlockValidation *request_as_BlockValidation() const {
    return request_type() == proof::ValidationUnion_BlockValidation ? static_cast<const proof::BlockValidation *>(request()) : nullptr;
  }
  const proof::ModelValidation *request_as_ModelValidation() const {
    return request_type() == proof::ValidationUnion_ModelValidation ? static_cast<const proof::ModelValidation *>(request()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_HASH_ID) &&
           verifier.VerifyVector(hash_id()) &&
           VerifyField<uint8_t>(verifier, VT_VALIDATION_TYPE, 1) &&
           VerifyField<uint8_t>(verifier, VT_REQUEST_TYPE, 1) &&
           VerifyOffset(verifier, VT_REQUEST) &&
           VerifyValidationUnion(verifier, request(), request_type()) &&
           verifier.EndTable();
  }
};

template<> inline const proof::BlockValidation *ValidationRequest::request_as<proof::BlockValidation>() const {
  return request_as_BlockValidation();
}

template<> inline const proof::ModelValidation *ValidationRequest::request_as<proof::ModelValidation>() const {
  return request_as_ModelValidation();
}

struct ValidationRequestBuilder {
  typedef ValidationRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_hash_id(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> hash_id) {
    fbb_.AddOffset(ValidationRequest::VT_HASH_ID, hash_id);
  }
  void add_validation_type(proof::ValidationType validation_type) {
    fbb_.AddElement<uint8_t>(ValidationRequest::VT_VALIDATION_TYPE, static_cast<uint8_t>(validation_type), 0);
  }
  void add_request_type(proof::ValidationUnion request_type) {
    fbb_.AddElement<uint8_t>(ValidationRequest::VT_REQUEST_TYPE, static_cast<uint8_t>(request_type), 0);
  }
  void add_request(::flatbuffers::Offset<void> request) {
    fbb_.AddOffset(ValidationRequest::VT_REQUEST, request);
  }
  explicit ValidationRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ValidationRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ValidationRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ValidationRequest> CreateValidationRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> hash_id = 0,
    proof::ValidationType validation_type = proof::ValidationType_Quick,
    proof::ValidationUnion request_type = proof::ValidationUnion_NONE,
    ::flatbuffers::Offset<void> request = 0) {
  ValidationRequestBuilder builder_(_fbb);
  builder_.add_request(request);
  builder_.add_hash_id(hash_id);
  builder_.add_request_type(request_type);
  builder_.add_validation_type(validation_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ValidationRequest> CreateValidationRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *hash_id = nullptr,
    proof::ValidationType validation_type = proof::ValidationType_Quick,
    proof::ValidationUnion request_type = proof::ValidationUnion_NONE,
    ::flatbuffers::Offset<void> request = 0) {
  auto hash_id__ = hash_id ? _fbb.CreateVector<uint8_t>(*hash_id) : 0;
  return proof::CreateValidationRequest(
      _fbb,
      hash_id__,
      validation_type,
      request_type,
      request);
}

struct ValidationResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ValidationResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HASH_IDENTIFIER = 4,
    VT_ENUM_RESPONSE = 6
  };
  const ::flatbuffers::Vector<uint8_t> *hash_identifier() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_HASH_IDENTIFIER);
  }
  proof::ResponseValue enum_response() const {
    return static_cast<proof::ResponseValue>(GetField<uint8_t>(VT_ENUM_RESPONSE, 0));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_HASH_IDENTIFIER) &&
           verifier.VerifyVector(hash_identifier()) &&
           VerifyField<uint8_t>(verifier, VT_ENUM_RESPONSE, 1) &&
           verifier.EndTable();
  }
};

struct ValidationResponseBuilder {
  typedef ValidationResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_hash_identifier(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> hash_identifier) {
    fbb_.AddOffset(ValidationResponse::VT_HASH_IDENTIFIER, hash_identifier);
  }
  void add_enum_response(proof::ResponseValue enum_response) {
    fbb_.AddElement<uint8_t>(ValidationResponse::VT_ENUM_RESPONSE, static_cast<uint8_t>(enum_response), 0);
  }
  explicit ValidationResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ValidationResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ValidationResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ValidationResponse> CreateValidationResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> hash_identifier = 0,
    proof::ResponseValue enum_response = proof::ResponseValue_Quick_OK) {
  ValidationResponseBuilder builder_(_fbb);
  builder_.add_hash_identifier(hash_identifier);
  builder_.add_enum_response(enum_response);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ValidationResponse> CreateValidationResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *hash_identifier = nullptr,
    proof::ResponseValue enum_response = proof::ResponseValue_Quick_OK) {
  auto hash_identifier__ = hash_identifier ? _fbb.CreateVector<uint8_t>(*hash_identifier) : 0;
  return proof::CreateValidationResponse(
      _fbb,
      hash_identifier__,
      enum_response);
}

inline bool VerifyValidationUnion(::flatbuffers::Verifier &verifier, const void *obj, ValidationUnion type) {
  switch (type) {
    case ValidationUnion_NONE: {
      return true;
    }
    case ValidationUnion_BlockValidation: {
      auto ptr = reinterpret_cast<const proof::BlockValidation *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ValidationUnion_ModelValidation: {
      auto ptr = reinterpret_cast<const proof::ModelValidation *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyValidationUnionVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyValidationUnion(
        verifier,  values->Get(i), types->GetEnum<ValidationUnion>(i))) {
      return false;
    }
  }
  return true;
}

inline const proof::ValidationRequest *GetValidationRequest(const void *buf) {
  return ::flatbuffers::GetRoot<proof::ValidationRequest>(buf);
}

inline const proof::ValidationRequest *GetSizePrefixedValidationRequest(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<proof::ValidationRequest>(buf);
}

inline bool VerifyValidationRequestBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<proof::ValidationRequest>(nullptr);
}

inline bool VerifySizePrefixedValidationRequestBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<proof::ValidationRequest>(nullptr);
}

inline void FinishValidationRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<proof::ValidationRequest> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedValidationRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<proof::ValidationRequest> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace proof

#endif  // FLATBUFFERS_GENERATED_VALIDATION_PROOF_H_
