#ifndef BITCOIN_TEST_UTIL_GOLDEN_VECTOR_LOADER_H
#define BITCOIN_TEST_UTIL_GOLDEN_VECTOR_LOADER_H

#include <crypto/groth16.h>
#include <uint256.h>
#include <util/strencodings.h>

#include <optional>
#include <string>
#include <vector>

namespace golden_vectors {

/**
 * Golden vector loaded from shared-utils/kyc-prover/vectors/golden_vectors.json
 * Contains REAL BLS12-381 Groth16 proofs generated by gnark
 */
struct GoldenVector {
    std::string name;

    // Witness data
    struct Witness {
        std::string secret;
        std::string pubkey_hash;
        uint32_t country;
        uint32_t age;
        std::vector<std::string> merkle_proof;
        uint32_t merkle_index;
        std::string merkle_leaf_hash;
        std::string chain_separator;
        std::string asset_id;
        std::string compliance_root;
        std::string tfr_anchor;
    } witness;

    // Real proof data (192 bytes)
    std::vector<unsigned char> proof_bytes;

    // Public inputs (N x 32 bytes: 128 for legacy, 192 for HDv1)
    std::vector<unsigned char> public_inputs_bytes;

    // Verification key in the custom C++ format (size varies by circuit family)
    std::vector<unsigned char> vk_bytes;

    // Whether this vector should fail proof generation
    bool should_fail;

    // Helper: Extract chain separator from public inputs
    uint256 GetChainSeparator() const {
        if (public_inputs_bytes.size() < 32) return uint256();
        uint256 result;
        std::copy(public_inputs_bytes.begin(), public_inputs_bytes.begin() + 32, result.begin());
        return result;
    }

    // Helper: Extract asset ID from public inputs
    uint256 GetAssetId() const {
        if (public_inputs_bytes.size() < 64) return uint256();
        uint256 result;
        std::copy(public_inputs_bytes.begin() + 32, public_inputs_bytes.begin() + 64, result.begin());
        return result;
    }

    // Helper: Extract root height from public inputs (element 2, last 4 bytes)
    // Legacy 4-input circuits only — HDv1 does not pack height into the root.
    uint32_t GetRootHeight() const {
        if (public_inputs_bytes.size() < 96) return 0;
        const unsigned char* elem2 = public_inputs_bytes.data() + 64;
        return (static_cast<uint32_t>(elem2[28]) << 24) |
               (static_cast<uint32_t>(elem2[29]) << 16) |
               (static_cast<uint32_t>(elem2[30]) << 8) |
               static_cast<uint32_t>(elem2[31]);
    }

    // Helper: Extract TFR anchor from public inputs
    uint256 GetTfrAnchor() const {
        if (public_inputs_bytes.size() < 128) return uint256();
        uint256 result;
        std::copy(public_inputs_bytes.begin() + 96, public_inputs_bytes.begin() + 128, result.begin());
        return result;
    }

    // Helper: Detect HDv1 circuit (6 public inputs = 192 bytes)
    bool IsHDv1() const {
        return public_inputs_bytes.size() == 192;
    }

    // Helper: Extract output key high (element 4) — HDv1 only
    // Returns the 16-byte key half from the lower 16 bytes of the 32-byte field element
    std::vector<unsigned char> GetOutputKeyHigh() const {
        if (public_inputs_bytes.size() < 160) return {};
        // Field element at [128:160], key half is in bytes [16:32] of the element
        return std::vector<unsigned char>(
            public_inputs_bytes.begin() + 128 + 16,
            public_inputs_bytes.begin() + 160);
    }

    // Helper: Extract output key low (element 5) — HDv1 only
    std::vector<unsigned char> GetOutputKeyLow() const {
        if (public_inputs_bytes.size() < 192) return {};
        return std::vector<unsigned char>(
            public_inputs_bytes.begin() + 160 + 16,
            public_inputs_bytes.begin() + 192);
    }

    // Helper: Reconstruct full 32-byte x-only key from high/low halves — HDv1 only
    std::vector<unsigned char> GetXOnlyOutputKey() const {
        auto high = GetOutputKeyHigh();
        auto low = GetOutputKeyLow();
        if (high.size() != 16 || low.size() != 16) return {};
        std::vector<unsigned char> key;
        key.insert(key.end(), high.begin(), high.end());
        key.insert(key.end(), low.begin(), low.end());
        return key;
    }

    // Helper: Get pure compliance root (element 2) — works for both legacy and HDv1
    uint256 GetComplianceRoot() const {
        if (public_inputs_bytes.size() < 96) return uint256();
        uint256 result;
        std::copy(public_inputs_bytes.begin() + 64, public_inputs_bytes.begin() + 96, result.begin());
        return result;
    }
};

/**
 * Load a golden vector by name from JSON file
 *
 * @param vector_name Name of vector ("valid", "invalid_secret", etc.)
 * @param json_path Path to golden_vectors.json (default: auto-detect from repo root)
 * @return GoldenVector if found, std::nullopt otherwise
 */
std::optional<GoldenVector> LoadGoldenVector(
    const std::string& vector_name,
    const std::string& json_path = ""
);

/**
 * Load all golden vectors from JSON file
 *
 * @param json_path Path to golden_vectors.json (default: auto-detect from repo root)
 * @return Vector of all loaded vectors
 */
std::vector<GoldenVector> LoadAllGoldenVectors(const std::string& json_path = "");

/**
 * Check if golden vectors are available
 * Useful for conditionally enabling tests that require real proof data
 */
bool GoldenVectorsAvailable(const std::string& json_path = "");

/**
 * Get default path to golden_vectors.json (legacy 4-input circuits)
 */
std::string GetDefaultGoldenVectorsPath();

/**
 * Get default path to golden_vectors_hd_v1.json (HDv1 6-input circuit)
 */
std::string GetDefaultHDV1GoldenVectorsPath();

/**
 * Load HDv1 golden vectors using the HDv1-specific path
 */
inline std::optional<GoldenVector> LoadHDV1GoldenVector(const std::string& vector_name) {
    return LoadGoldenVector(vector_name, GetDefaultHDV1GoldenVectorsPath());
}

inline std::vector<GoldenVector> LoadAllHDV1GoldenVectors() {
    return LoadAllGoldenVectors(GetDefaultHDV1GoldenVectorsPath());
}

inline bool HDV1GoldenVectorsAvailable() {
    return GoldenVectorsAvailable(GetDefaultHDV1GoldenVectorsPath());
}

} // namespace golden_vectors

#endif // BITCOIN_TEST_UTIL_GOLDEN_VECTOR_LOADER_H
