// @generated by gen_bcred_table.py — DO NOT EDIT BY HAND.
//
// R=1024 B_cred credit-threshold table (TIP-0003).
// BCRED_THRESHOLD_Q63[n] == floor(2^63 * 2^(-n/R)) for n = 0 .. 32*R.
#ifndef POW_V3_BCRED_TABLE_R1024_H
#define POW_V3_BCRED_TABLE_R1024_H

#include <cstdint>
#include <cstddef>

namespace pow_v3 {

constexpr std::size_t BCRED_R = 1024;
constexpr std::size_t BCRED_N_MAX = 32768;
constexpr std::size_t BCRED_TABLE_LEN = 32769;

// SHA-256 of the little-endian uint64 encoding of BCRED_THRESHOLD_Q63 — the
// consensus table identity, identical to bcred_table_r1024.py's constant. The
// cross-language vector test re-hashes the compiled array and asserts it
// equals this string (and equals the Python table's SHA).
extern const char* const BCRED_TABLE_SHA256_HEX;

extern const uint64_t BCRED_THRESHOLD_Q63[BCRED_TABLE_LEN];

}  // namespace pow_v3

#endif  // POW_V3_BCRED_TABLE_R1024_H
