#!/usr/bin/env bash
# Simple wrapper to run functional tests inside the Docker image (or locally)
# - Ensures test/config.ini exists
# - Passes through args to test_runner.py
# - Adds sensible defaults: jobs, tmpdir from TC_TMPDIR if set
#
# Usage:
#   ./run_functional.sh                    # Run all tests
#   ./run_functional.sh feature_block      # Run single test
#   ./run_functional.sh test1 test2        # Run multiple specific tests
#   ./run_functional.sh --help             # Show test_runner.py help

set -euo pipefail

COSIGN_TOR_TESTMODE="${COSIGN_TOR_TESTMODE:-1}"
export COSIGN_TOR_TESTMODE

TOR_DATA_DIR="${TOR_DATA_DIR:-/var/lib/tor}"
TOR_SOCKS_ADDR="${TOR_SOCKS_ADDR:-127.0.0.1:9050}"
TOR_SOCKS_HOST="${TOR_SOCKS_ADDR%:*}"
TOR_SOCKS_PORT="${TOR_SOCKS_ADDR#*:}"
TOR_HS_DIR="${TOR_HS_DIR:-$TOR_DATA_DIR/tensorcash-cosign}"
TOR_CONFIG_FILE=""
TOR_LOG_FILE="/tmp/tor-functional.log"

prepare_tor_config() {
  TOR_CONFIG_FILE="/tmp/torrc-tensorcash-functional"

  mkdir -p "$TOR_DATA_DIR" "$TOR_HS_DIR"
  chmod 700 "$TOR_DATA_DIR" "$TOR_HS_DIR" 2>/dev/null || true
  local user_line=""
  if id -u debian-tor >/dev/null 2>&1; then
    chown debian-tor:debian-tor "$TOR_DATA_DIR" "$TOR_HS_DIR" 2>/dev/null || true
    user_line="User debian-tor"
  fi

  cat >"$TOR_CONFIG_FILE" <<CONF
# Auto-generated by run_functional.sh for functional testing
DataDirectory $TOR_DATA_DIR
SocksPort $TOR_SOCKS_ADDR
Log notice file $TOR_LOG_FILE
Log notice stderr
$user_line

# Control port for dynamic hidden service management
# Allows cosign-bridge to create ephemeral hidden services
ControlPort 9051
CookieAuthentication 1
CookieAuthFileGroupReadable 1

# Static hidden service configuration (fallback)
HiddenServiceDir $TOR_HS_DIR
HiddenServiceVersion 3
HiddenServicePort 9735 127.0.0.1:9735

# Performance tuning for testing
# Reduce timeouts to speed up circuit building
LearnCircuitBuildTimeout 0
CircuitBuildTimeout 10
CircuitsAvailableTimeout 10

# Allow connecting to .onion addresses we host (for testing in same container)
HiddenServiceAllowUnknownPorts 1
CONF
}

wait_for_socks_proxy() {
  local host="$TOR_SOCKS_HOST"
  local port="$TOR_SOCKS_PORT"

  echo -n "Waiting for Tor SOCKS5 proxy on ${host}:${port}"
  for _ in $(seq 1 40); do
    if python3 - <<PY >/dev/null 2>&1; then
import socket, sys
HOST = "${host}"
PORT = int("${port}")
try:
    with socket.create_connection((HOST, PORT), timeout=0.5):
        pass
except OSError:
    sys.exit(1)
PY
      echo " ... ready"
      return 0
    fi
    sleep 1
    echo -n "."
  done

  echo "" >&2
  echo "ERROR: Timed out waiting for Tor SOCKS5 proxy on ${host}:${port}" >&2
  exit 1
}

wait_for_control_port() {
  echo -n "Waiting for Tor control port on 127.0.0.1:9051"
  for _ in $(seq 1 20); do
    if python3 - <<PY >/dev/null 2>&1; then
import socket, sys
try:
    with socket.create_connection(("127.0.0.1", 9051), timeout=0.5):
        pass
except OSError:
    sys.exit(1)
PY
      echo " ... ready"
      # Make cookie file readable by all (for testing only)
      chmod 644 "$TOR_DATA_DIR/control_auth_cookie" 2>/dev/null || true
      return 0
    fi
    sleep 1
    echo -n "."
  done

  echo "" >&2
  echo "WARNING: Tor control port not ready" >&2
  return 0
}

wait_for_hidden_service() {
  local hostname_file="$TOR_HS_DIR/hostname"

  echo -n "Waiting for Tor hidden service hostname at ${hostname_file}"
  for _ in $(seq 1 40); do
    if [[ -s "$hostname_file" ]]; then
      local onion
      onion=$(tr -d '\n' < "$hostname_file")
      echo " ... ready (${onion})"
      return 0
    fi
    sleep 1
    echo -n "."
  done

  echo "" >&2
  echo "ERROR: Hidden service hostname not created at ${hostname_file}" >&2
  exit 1
}

wait_for_tor_bootstrap() {
  echo -n "Waiting for Tor to bootstrap to the network"

  # In non-anonymous mode, Tor should bootstrap very quickly
  # Check for bootstrap completion in log file
  for i in $(seq 1 60); do
    if [[ -f "$TOR_LOG_FILE" ]] && grep -q "Bootstrapped 100" "$TOR_LOG_FILE" 2>/dev/null; then
      echo " ... bootstrapped (${i}s)"
      return 0
    fi

    # Also check for "Done" message which indicates full bootstrap
    if [[ -f "$TOR_LOG_FILE" ]] && grep -q "Bootstrapped 100%.*Done" "$TOR_LOG_FILE" 2>/dev/null; then
      echo " ... bootstrapped (${i}s)"
      return 0
    fi

    sleep 1
    if [[ $((i % 10)) -eq 0 ]]; then
      echo -n " [${i}s]"
    else
      echo -n "."
    fi
  done

  echo "" >&2
  echo "WARNING: Tor may not be fully bootstrapped after 60s" >&2
  echo "This might cause test failures when connecting to .onion addresses" >&2

  # Show last few log lines for debugging
  if [[ -f "$TOR_LOG_FILE" ]]; then
    echo "Last 10 lines of Tor log:" >&2
    tail -10 "$TOR_LOG_FILE" >&2
  fi

  # Don't fail - let tests proceed anyway
  return 0
}

ensure_tor_daemon() {
  if ! command -v tor >/dev/null 2>&1; then
    echo "ERROR: tor binary not found on PATH; cannot run Tor transport tests" >&2
    exit 1
  fi

  prepare_tor_config

  local tor_pids=""
  if command -v pgrep >/dev/null 2>&1; then
    tor_pids=$(pgrep -x tor 2>/dev/null || true)
  else
    tor_pids=$(ps -eo comm,pid 2>/dev/null | awk '$1=="tor"{print $2}' | tr '\n' ' ')
  fi

  if [[ -n "${tor_pids// /}" ]]; then
    echo "Tor daemon already running (pid(s): $(echo "$tor_pids" | tr '\n' ' '))"
    echo "Restarting Tor with functional test config..."
    kill $tor_pids >/dev/null 2>&1 || true
    sleep 2  # Give Tor time to fully stop and release ports

    # Clear old log file
    rm -f "$TOR_LOG_FILE"

    tor -f "$TOR_CONFIG_FILE" --RunAsDaemon 1
  else
    echo "Starting Tor daemon for functional tests..."

    # Clear old log file
    rm -f "$TOR_LOG_FILE"

    tor -f "$TOR_CONFIG_FILE" --RunAsDaemon 1
  fi

  wait_for_socks_proxy
  wait_for_control_port
  wait_for_tor_bootstrap
  wait_for_hidden_service

  echo "Tor daemon ready:"
  echo "  SOCKS proxy: $TOR_SOCKS_ADDR"
  echo "  Control port: 127.0.0.1:9051"
  echo "  Hidden service: $(cat $TOR_HS_DIR/hostname 2>/dev/null || echo 'not ready')"
}

# Check for help flag first
if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  echo "Usage: $0 [test_name] [test_name2] ... [options]"
  echo ""
  echo "Examples:"
  echo "  $0                           # Run all functional tests"
  echo "  $0 feature_block             # Run single test"
  echo "  $0 p2p_* wallet_*            # Run tests matching patterns"
  echo "  $0 --list                    # List all available tests"
  echo ""
  echo "Environment variables:"
  echo "  JOBS=N                       # Number of parallel jobs (default: 2)"
  echo "  FULL_TESTS=1                 # Run all tests including incompatible ones"
  echo "  NO_CACHE=1                   # Force sequential run, skip cache"
  echo "  TC_TMPDIR=/path              # Custom temp directory"
  echo ""
  echo "Passing --help through to test_runner.py for full options..."
  echo ""
fi

BUILD_DIR="${BUILD_DIR:-/build/bcore/build}"
BASE_DIR="${BASE_DIR:-/build/bcore}"
TEST_DIR="$BASE_DIR/test"
RUNNER="$TEST_DIR/functional/test_runner.py"

mkdir -p "$TEST_DIR"

# Create config.ini if missing
if [ ! -f "$TEST_DIR/config.ini" ]; then
  cat >"$TEST_DIR/config.ini" <<CONFIG
[environment]
BUILDDIR=$BUILD_DIR
SRCDIR=$BASE_DIR
EXEEXT=
CLIENT_NAME=Bitcoin Core
# Used by the framework to print bugreport info on failure
CLIENT_BUGREPORT=https://github.com/tensorcash/tensorcash/issues
[components]
ENABLE_WALLET=true
ENABLE_CLI=true
ENABLE_BITCOIND=true
ENABLE_ZMQ=true
ENABLE_EXTERNAL_SIGNER=true
CONFIG
fi

cd "$TEST_DIR"

# Defaults
JOBS="${JOBS:-2}"
TIMEOUT_FACTOR="${TIMEOUT_FACTOR:-4}"
RUNNER_ARGS=("-j" "$JOBS")

if [[ "${COSIGN_TOR_TESTMODE}" != "1" ]]; then
  ensure_tor_daemon
else
  echo "Skipping Tor daemon startup (COSIGN_TOR_TESTMODE=${COSIGN_TOR_TESTMODE})"
fi

# If TC_TMPDIR set and no -t provided, wire it through
if [[ -n "${TC_TMPDIR:-}" ]]; then
  have_t_flag="0"
  for a in "$@"; do
    if [[ "$a" == "-t" || "$a" == "--tmpdirprefix" ]]; then
      have_t_flag="1"
      break
    fi
  done
  if [[ "$have_t_flag" == "0" ]]; then
    mkdir -p "$TC_TMPDIR"
    RUNNER_ARGS+=("-t" "$TC_TMPDIR")
  fi
fi

echo "Running functional tests via test_runner.py"
echo "  BUILDDIR=$BUILD_DIR"
echo "  SRCDIR=$BASE_DIR"
echo "  JOBS=$JOBS"
echo "  TIMEOUT_FACTOR=$TIMEOUT_FACTOR"
if [[ "$#" -gt 0 && "${1:-}" != "--"* ]]; then
  echo "  TESTS: $*"
fi

# Default node args for functional runs (keep tests strict, avoid external deps)
if [[ -z "${TC_NODE_ARGS:-}" ]]; then
  # Notes:
  # - useextapi=0 disables the external mining ZMQ binding which otherwise causes timeouts.
  # - validationapi=mock forces deterministic in-process validation on mockable chains.
  # - mockval-default-quick=quick_ok_smell_ok pre-approves sampling quick checks so
  #   functional tests do not stall waiting for asynchronous external verdicts.
  # - debug=1 enables debug logging to diagnose validation failures
  # - Do NOT relax mempool policy by default (no acceptnonstdtxn here) to keep tests strict.
  export TC_NODE_ARGS="assetsheight=0 useextapi=0 validationapi=mock mockval-default-quick=quick_ok_smell_ok mockval-preapprove-genesis=1 debug=1"
fi

# If FULL_TESTS=1, do not apply excludes; otherwise honor known_incompatible list
if [[ "${FULL_TESTS:-0}" != "1" ]]; then
  EXCLUDES_FILE="${EXCLUDES_FILE:-$BASE_DIR/test-runner/known_incompatible.txt}"
  if [[ -f "$EXCLUDES_FILE" ]]; then
    EXCLUDES=$(grep -vE '^(#|\s*$)' "$EXCLUDES_FILE" | paste -sd, -)
    if [[ -n "$EXCLUDES" ]]; then
      RUNNER_ARGS+=("--exclude" "$EXCLUDES")
    fi
  fi
fi

# If NO_CACHE=1 or TC_NO_CACHE=1, force sequential run to avoid cache pre-generation
if [[ "${NO_CACHE:-${TC_NO_CACHE:-}}" == "1" ]]; then
  echo "NO_CACHE=1 detected: forcing JOBS=1 to skip cache pre-generation"
  RUNNER_ARGS=("-j" "1")
fi

# If user provided multiple tests and did not explicitly set JOBS, default to 1 to avoid cache
if [[ "$#" -gt 1 ]] && [[ -z "${JOBS+x}" ]]; then
  echo "Multiple tests detected with no explicit JOBS: using -j 1 to skip cache"
  RUNNER_ARGS=("-j" "1")
fi

set +e
python3 "$RUNNER" "${RUNNER_ARGS[@]}" --timeout-factor="$TIMEOUT_FACTOR" "$@"
RC=$?
set -e
exit $RC
