"""Vendored FlatBuffers-generated Python for the TensorCash proof schema.

Proof.py / MiningResponse.py / FloatArray.py / UIntArray.py are copied from
tensorcash/shared-utils/fb-schemas/proof/ (generated by flatc from
proof.fbs + blockheader.fbs). They are vendored so bcore's functional tests
can build proof::Proof / proof::MiningResponse buffers — and parse them back
— without reaching outside this repository.

The ONLY change from the generated originals: the four nested-table reader
imports (`from proof.Proof import Proof` etc.) were repointed to
`test_framework.proof_fb.*` so the readers resolve from this vendored
location instead of an absent top-level `proof` package. Each repointed
line is tagged `# vendored: repointed from ...`. When re-vendoring after a
proof.fbs change, re-apply that repointing (grep `from proof\.`). The
module-level builder functions (ProofStart / MiningResponseEnd / ...) have
no cross-module imports and were untouched.

Requires the `flatbuffers` pip package; importers must guard for its
absence (mirroring the optional chiavdf dependency in vdf_helper.py).
"""
