# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proof

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MiningResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MiningResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMiningResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MiningResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MiningResponse
    def ReqId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MiningResponse
    def Nonce(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MiningResponse
    def AdjustedBits(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MiningResponse
    def PowBlobHash(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # MiningResponse
    def PowBlobHashAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # MiningResponse
    def PowBlobHashLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MiningResponse
    def PowBlobHashIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # MiningResponse
    def Difficulty(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # MiningResponse
    def PowBlob(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from test_framework.proof_fb.Proof import Proof  # vendored: repointed from `proof.Proof`
            obj = Proof()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MiningResponse
    def CompletionId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def MiningResponseStart(builder):
    builder.StartObject(7)

def Start(builder):
    MiningResponseStart(builder)

def MiningResponseAddReqId(builder, reqId):
    builder.PrependUint32Slot(0, reqId, 0)

def AddReqId(builder, reqId):
    MiningResponseAddReqId(builder, reqId)

def MiningResponseAddNonce(builder, nonce):
    builder.PrependUint32Slot(1, nonce, 0)

def AddNonce(builder, nonce):
    MiningResponseAddNonce(builder, nonce)

def MiningResponseAddAdjustedBits(builder, adjustedBits):
    builder.PrependUint32Slot(2, adjustedBits, 0)

def AddAdjustedBits(builder, adjustedBits):
    MiningResponseAddAdjustedBits(builder, adjustedBits)

def MiningResponseAddPowBlobHash(builder, powBlobHash):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(powBlobHash), 0)

def AddPowBlobHash(builder, powBlobHash):
    MiningResponseAddPowBlobHash(builder, powBlobHash)

def MiningResponseStartPowBlobHashVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartPowBlobHashVector(builder, numElems):
    return MiningResponseStartPowBlobHashVector(builder, numElems)

def MiningResponseAddDifficulty(builder, difficulty):
    builder.PrependUint32Slot(4, difficulty, 0)

def AddDifficulty(builder, difficulty):
    MiningResponseAddDifficulty(builder, difficulty)

def MiningResponseAddPowBlob(builder, powBlob):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(powBlob), 0)

def AddPowBlob(builder, powBlob):
    MiningResponseAddPowBlob(builder, powBlob)

def MiningResponseAddCompletionId(builder, completionId):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(completionId), 0)

def AddCompletionId(builder, completionId):
    MiningResponseAddCompletionId(builder, completionId)

def MiningResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return MiningResponseEnd(builder)
