# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proof

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Proof(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Proof()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProof(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ProofBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x50\x52\x4F\x46", size_prefixed=size_prefixed)

    # Proof
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Proof
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Proof
    def Tick(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Proof
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Proof
    def Target(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Proof
    def TargetAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Proof
    def TargetLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Proof
    def TargetIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Proof
    def Vdf(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Proof
    def VdfAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Proof
    def VdfLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Proof
    def VdfIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # Proof
    def Hash(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Proof
    def HashAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Proof
    def HashLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Proof
    def HashIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # Proof
    def BlockHash(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Proof
    def BlockHashAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Proof
    def BlockHashLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Proof
    def BlockHashIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # Proof
    def HeaderPrefix(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Proof
    def HeaderPrefixAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Proof
    def HeaderPrefixLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Proof
    def HeaderPrefixIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # Proof
    def IsSolution(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Proof
    def ModelIdentifier(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Proof
    def ComputePrecision(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Proof
    def IpfsCid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Proof
    def ExtraFlags(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Proof
    def Temperature(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Proof
    def TopP(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Proof
    def TopK(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Proof
    def RepetitionPenalty(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Proof
    def ChosenTokens(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Proof
    def ChosenTokensAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Proof
    def ChosenTokensLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Proof
    def ChosenTokensIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        return o == 0

    # Proof
    def ChosenProbs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Proof
    def ChosenProbsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # Proof
    def ChosenProbsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Proof
    def ChosenProbsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        return o == 0

    # Proof
    def SamplingU(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Proof
    def SamplingUAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # Proof
    def SamplingULength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Proof
    def SamplingUIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        return o == 0

    # Proof
    def SoftmaxNormalizers(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Proof
    def SoftmaxNormalizersAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # Proof
    def SoftmaxNormalizersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Proof
    def SoftmaxNormalizersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        return o == 0

    # Proof
    def PromptTokens(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Proof
    def PromptTokensAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # Proof
    def PromptTokensLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Proof
    def PromptTokensIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        return o == 0

    # Proof
    def PadMask(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.BoolFlags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Proof
    def PadMaskAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.BoolFlags, o)
        return 0

    # Proof
    def PadMaskLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Proof
    def PadMaskIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        return o == 0

    # Proof
    def TopkLogits(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from test_framework.proof_fb.FloatArray import FloatArray  # vendored: repointed from `proof.FloatArray`
            obj = FloatArray()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Proof
    def TopkLogitsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Proof
    def TopkLogitsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        return o == 0

    # Proof
    def TopkIndices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from test_framework.proof_fb.UIntArray import UIntArray  # vendored: repointed from `proof.UIntArray`
            obj = UIntArray()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Proof
    def TopkIndicesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Proof
    def TopkIndicesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        return o == 0

    # Proof
    def LogsumexpStats(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from test_framework.proof_fb.FloatArray import FloatArray  # vendored: repointed from `proof.FloatArray`
            obj = FloatArray()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Proof
    def LogsumexpStatsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Proof
    def LogsumexpStatsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        return o == 0

def ProofStart(builder):
    builder.StartObject(26)

def Start(builder):
    ProofStart(builder)

def ProofAddVersion(builder, version):
    builder.PrependUint8Slot(0, version, 0)

def AddVersion(builder, version):
    ProofAddVersion(builder, version)

def ProofAddTick(builder, tick):
    builder.PrependUint64Slot(1, tick, 0)

def AddTick(builder, tick):
    ProofAddTick(builder, tick)

def ProofAddTimestamp(builder, timestamp):
    builder.PrependUint64Slot(2, timestamp, 0)

def AddTimestamp(builder, timestamp):
    ProofAddTimestamp(builder, timestamp)

def ProofAddTarget(builder, target):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(target), 0)

def AddTarget(builder, target):
    ProofAddTarget(builder, target)

def ProofStartTargetVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartTargetVector(builder, numElems):
    return ProofStartTargetVector(builder, numElems)

def ProofAddVdf(builder, vdf):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(vdf), 0)

def AddVdf(builder, vdf):
    ProofAddVdf(builder, vdf)

def ProofStartVdfVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartVdfVector(builder, numElems):
    return ProofStartVdfVector(builder, numElems)

def ProofAddHash(builder, hash):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(hash), 0)

def AddHash(builder, hash):
    ProofAddHash(builder, hash)

def ProofStartHashVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartHashVector(builder, numElems):
    return ProofStartHashVector(builder, numElems)

def ProofAddBlockHash(builder, blockHash):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(blockHash), 0)

def AddBlockHash(builder, blockHash):
    ProofAddBlockHash(builder, blockHash)

def ProofStartBlockHashVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartBlockHashVector(builder, numElems):
    return ProofStartBlockHashVector(builder, numElems)

def ProofAddHeaderPrefix(builder, headerPrefix):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(headerPrefix), 0)

def AddHeaderPrefix(builder, headerPrefix):
    ProofAddHeaderPrefix(builder, headerPrefix)

def ProofStartHeaderPrefixVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartHeaderPrefixVector(builder, numElems):
    return ProofStartHeaderPrefixVector(builder, numElems)

def ProofAddIsSolution(builder, isSolution):
    builder.PrependBoolSlot(8, isSolution, 0)

def AddIsSolution(builder, isSolution):
    ProofAddIsSolution(builder, isSolution)

def ProofAddModelIdentifier(builder, modelIdentifier):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(modelIdentifier), 0)

def AddModelIdentifier(builder, modelIdentifier):
    ProofAddModelIdentifier(builder, modelIdentifier)

def ProofAddComputePrecision(builder, computePrecision):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(computePrecision), 0)

def AddComputePrecision(builder, computePrecision):
    ProofAddComputePrecision(builder, computePrecision)

def ProofAddIpfsCid(builder, ipfsCid):
    builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(ipfsCid), 0)

def AddIpfsCid(builder, ipfsCid):
    ProofAddIpfsCid(builder, ipfsCid)

def ProofAddExtraFlags(builder, extraFlags):
    builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(extraFlags), 0)

def AddExtraFlags(builder, extraFlags):
    ProofAddExtraFlags(builder, extraFlags)

def ProofAddTemperature(builder, temperature):
    builder.PrependFloat32Slot(13, temperature, 0.0)

def AddTemperature(builder, temperature):
    ProofAddTemperature(builder, temperature)

def ProofAddTopP(builder, topP):
    builder.PrependFloat32Slot(14, topP, 0.0)

def AddTopP(builder, topP):
    ProofAddTopP(builder, topP)

def ProofAddTopK(builder, topK):
    builder.PrependUint32Slot(15, topK, 0)

def AddTopK(builder, topK):
    ProofAddTopK(builder, topK)

def ProofAddRepetitionPenalty(builder, repetitionPenalty):
    builder.PrependFloat32Slot(16, repetitionPenalty, 0.0)

def AddRepetitionPenalty(builder, repetitionPenalty):
    ProofAddRepetitionPenalty(builder, repetitionPenalty)

def ProofAddChosenTokens(builder, chosenTokens):
    builder.PrependUOffsetTRelativeSlot(17, flatbuffers.number_types.UOffsetTFlags.py_type(chosenTokens), 0)

def AddChosenTokens(builder, chosenTokens):
    ProofAddChosenTokens(builder, chosenTokens)

def ProofStartChosenTokensVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartChosenTokensVector(builder, numElems):
    return ProofStartChosenTokensVector(builder, numElems)

def ProofAddChosenProbs(builder, chosenProbs):
    builder.PrependUOffsetTRelativeSlot(18, flatbuffers.number_types.UOffsetTFlags.py_type(chosenProbs), 0)

def AddChosenProbs(builder, chosenProbs):
    ProofAddChosenProbs(builder, chosenProbs)

def ProofStartChosenProbsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartChosenProbsVector(builder, numElems):
    return ProofStartChosenProbsVector(builder, numElems)

def ProofAddSamplingU(builder, samplingU):
    builder.PrependUOffsetTRelativeSlot(19, flatbuffers.number_types.UOffsetTFlags.py_type(samplingU), 0)

def AddSamplingU(builder, samplingU):
    ProofAddSamplingU(builder, samplingU)

def ProofStartSamplingUVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSamplingUVector(builder, numElems):
    return ProofStartSamplingUVector(builder, numElems)

def ProofAddSoftmaxNormalizers(builder, softmaxNormalizers):
    builder.PrependUOffsetTRelativeSlot(20, flatbuffers.number_types.UOffsetTFlags.py_type(softmaxNormalizers), 0)

def AddSoftmaxNormalizers(builder, softmaxNormalizers):
    ProofAddSoftmaxNormalizers(builder, softmaxNormalizers)

def ProofStartSoftmaxNormalizersVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSoftmaxNormalizersVector(builder, numElems):
    return ProofStartSoftmaxNormalizersVector(builder, numElems)

def ProofAddPromptTokens(builder, promptTokens):
    builder.PrependUOffsetTRelativeSlot(21, flatbuffers.number_types.UOffsetTFlags.py_type(promptTokens), 0)

def AddPromptTokens(builder, promptTokens):
    ProofAddPromptTokens(builder, promptTokens)

def ProofStartPromptTokensVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartPromptTokensVector(builder, numElems):
    return ProofStartPromptTokensVector(builder, numElems)

def ProofAddPadMask(builder, padMask):
    builder.PrependUOffsetTRelativeSlot(22, flatbuffers.number_types.UOffsetTFlags.py_type(padMask), 0)

def AddPadMask(builder, padMask):
    ProofAddPadMask(builder, padMask)

def ProofStartPadMaskVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartPadMaskVector(builder, numElems):
    return ProofStartPadMaskVector(builder, numElems)

def ProofAddTopkLogits(builder, topkLogits):
    builder.PrependUOffsetTRelativeSlot(23, flatbuffers.number_types.UOffsetTFlags.py_type(topkLogits), 0)

def AddTopkLogits(builder, topkLogits):
    ProofAddTopkLogits(builder, topkLogits)

def ProofStartTopkLogitsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTopkLogitsVector(builder, numElems):
    return ProofStartTopkLogitsVector(builder, numElems)

def ProofAddTopkIndices(builder, topkIndices):
    builder.PrependUOffsetTRelativeSlot(24, flatbuffers.number_types.UOffsetTFlags.py_type(topkIndices), 0)

def AddTopkIndices(builder, topkIndices):
    ProofAddTopkIndices(builder, topkIndices)

def ProofStartTopkIndicesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTopkIndicesVector(builder, numElems):
    return ProofStartTopkIndicesVector(builder, numElems)

def ProofAddLogsumexpStats(builder, logsumexpStats):
    builder.PrependUOffsetTRelativeSlot(25, flatbuffers.number_types.UOffsetTFlags.py_type(logsumexpStats), 0)

def AddLogsumexpStats(builder, logsumexpStats):
    ProofAddLogsumexpStats(builder, logsumexpStats)

def ProofStartLogsumexpStatsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartLogsumexpStatsVector(builder, numElems):
    return ProofStartLogsumexpStatsVector(builder, numElems)

def ProofEnd(builder):
    return builder.EndObject()

def End(builder):
    return ProofEnd(builder)
