# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proof

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UIntArray(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UIntArray()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUIntArray(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def UIntArrayBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x50\x52\x4F\x46", size_prefixed=size_prefixed)

    # UIntArray
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UIntArray
    def Values(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # UIntArray
    def ValuesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # UIntArray
    def ValuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UIntArray
    def ValuesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def UIntArrayStart(builder):
    builder.StartObject(1)

def Start(builder):
    UIntArrayStart(builder)

def UIntArrayAddValues(builder, values):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(values), 0)

def AddValues(builder, values):
    UIntArrayAddValues(builder, values)

def UIntArrayStartValuesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartValuesVector(builder, numElems):
    return UIntArrayStartValuesVector(builder, numElems)

def UIntArrayEnd(builder):
    return builder.EndObject()

def End(builder):
    return UIntArrayEnd(builder)
